// Types for Concursos section
export type CategoriaConcurso =
  | "vestibular"
  | "enem"
  | "federal"
  | "estadual"
  | "municipal"
  | "tribunais"
  | "militar";

export type TipoMaterial = "videoaula" | "questao" | "simulado" | "pdf" | "resumo";

export interface Questao {
  enunciado: string;
  alternativas: string[];
  respostaCorreta: number;
  explicacao: string;
  orgao?: string;
  ano?: number;
  dificuldade: "fácil" | "médio" | "difícil";
}

export interface MaterialConcurso {
  id: string;
  categoria: CategoriaConcurso;
  materia: string;
  titulo: string;
  tipo: TipoMaterial;
  descricao?: string;
  
  // Para videoaulas
  videoId?: string;
  duracao?: number;
  
  // Para questões
  questao?: Questao;
  
  // Para PDFs/Resumos
  conteudo?: string;
  urlDownload?: string;
}

export const CATEGORIAS_INFO = {
  vestibular: {
    nome: "Vestibulares",
    descricao: "FUVEST, UNICAMP, UNESP e mais",
    icon: "🎓",
    cor: "from-purple-600 to-purple-700",
    materias: ["Português", "Matemática", "Física", "Química", "Biologia", "História", "Geografia", "Inglês"],
  },
  enem: {
    nome: "ENEM",
    descricao: "Exame Nacional do Ensino Médio",
    icon: "📝",
    cor: "from-green-600 to-green-700",
    materias: ["Linguagens", "Matemática", "Ciências Humanas", "Ciências da Natureza", "Redação"],
  },
  federal: {
    nome: "Concursos Federais",
    descricao: "Receita, Polícia Federal, INSS e mais",
    icon: "🏛️",
    cor: "from-yellow-600 to-yellow-700",
    materias: ["Português", "Raciocínio Lógico", "Informática", "Direito Administrativo", "Direito Constitucional"],
  },
  estadual: {
    nome: "Concursos Estaduais",
    descricao: "PM, Bombeiros, Professor e mais",
    icon: "🚔",
    cor: "from-blue-600 to-blue-700",
    materias: ["Português", "Matemática", "Raciocínio Lógico", "Conhecimentos Específicos"],
  },
  municipal: {
    nome: "Concursos Municipais",
    descricao: "Prefeituras e órgãos municipais",
    icon: "🏢",
    cor: "from-indigo-600 to-indigo-700",
    materias: ["Português", "Matemática", "Conhecimentos Gerais", "Conhecimentos Específicos"],
  },
  tribunais: {
    nome: "Tribunais",
    descricao: "TJ, TRT, TST e mais",
    icon: "⚖️",
    cor: "from-red-600 to-red-700",
    materias: ["Português", "Raciocínio Lógico", "Direito Administrativo", "Direito Constitucional", "Informática"],
  },
  militar: {
    nome: "Carreira Militar",
    descricao: "ESA, EsPCEx, AFA e mais",
    icon: "🎖️",
    cor: "from-green-800 to-green-900",
    materias: ["Português", "Matemática", "Física", "Química", "Inglês", "História", "Geografia"],
  },
};

// Dados iniciais de videoaulas - Canais educacionais brasileiros verificados
export const concursosData: MaterialConcurso[] = [
  // ========== VESTIBULAR ==========
  // Português
  {
    id: "vest-port-1",
    categoria: "vestibular",
    materia: "Português",
    titulo: "Análise Sintática",
    tipo: "videoaula",
    descricao: "Como fazer análise sintática para vestibulares",
    videoId: "QCJ_G6_jAus",
    duracao: 15,
  },
  {
    id: "vest-port-2",
    categoria: "vestibular",
    materia: "Português",
    titulo: "Concordância Verbal e Nominal",
    tipo: "videoaula",
    descricao: "Regras de concordância para vestibular",
    videoId: "FzSsVDKgaXY",
    duracao: 12,
  },
  {
    id: "vest-port-3",
    categoria: "vestibular",
    materia: "Português",
    titulo: "Regência Verbal",
    tipo: "videoaula",
    descricao: "Principais regências verbais",
    videoId: "qk7_8CqUVgE",
    duracao: 14,
  },
  
  // Matemática
  {
    id: "vest-mat-1",
    categoria: "vestibular",
    materia: "Matemática",
    titulo: "Função Quadrática",
    tipo: "videoaula",
    descricao: "Parábolas e resolução de equações do 2º grau",
    videoId: "NPUPQ8VaZ8E",
    duracao: 20,
  },
  {
    id: "vest-mat-2",
    categoria: "vestibular",
    materia: "Matemática",
    titulo: "Trigonometria",
    tipo: "videoaula",
    descricao: "Seno, cosseno e tangente",
    videoId: "J91pp9WL77s",
    duracao: 18,
  },
  {
    id: "vest-mat-3",
    categoria: "vestibular",
    materia: "Matemática",
    titulo: "Regra de Três",
    tipo: "videoaula",
    descricao: "Simples e composta",
    videoId: "-3z9VTnWZ4Q",
    duracao: 16,
  },
  
  // ========== ENEM ==========
  // Redação
  {
    id: "enem-red-1",
    categoria: "enem",
    materia: "Redação",
    titulo: "Redação ENEM - Estrutura",
    tipo: "videoaula",
    descricao: "Como estruturar uma redação nota 1000",
    videoId: "1vEtlxjv7fk",
    duracao: 20,
  },
  {
    id: "enem-red-2",
    categoria: "enem",
    materia: "Redação",
    titulo: "Argumentação na Redação",
    tipo: "videoaula",
    descricao: "Como criar bons argumentos",
    videoId: "A-uzDgAIO5k",
    duracao: 18,
  },
  {
    id: "enem-red-3",
    categoria: "enem",
    materia: "Redação",
    titulo: "Proposta de Intervenção",
    tipo: "videoaula",
    descricao: "Como fazer uma proposta nota 1000",
    videoId: "DM9uOh3kbzE",
    duracao: 16,
  },
  
  // Matemática - Ordenado por PRIORIDADE (baseado em frequência ENEM 2020-2024)
  // 🔥 PRIORIDADE ALTA - Tópicos que mais caem (26-36 questões)
  {
    id: "enem-mat-1",
    categoria: "enem",
    materia: "Matemática",
    titulo: "🔥 Porcentagem e Matemática Financeira",
    tipo: "videoaula",
    descricao: "TOP 1 no ENEM! 8-10 questões por prova. Juros, descontos, acréscimos.",
    videoId: "-q-nHpRHeOw",
    duracao: 14,
  },
  {
    id: "enem-mat-2",
    categoria: "enem",
    materia: "Matemática",
    titulo: "🔥 Geometria Plana - Áreas e Perímetros",
    tipo: "videoaula",
    descricao: "TOP 2 no ENEM! 6-8 questões. Triângulos, quadrados, círculos, trapézios.",
    videoId: "1SDx6I8G114",
    duracao: 16,
  },
  {
    id: "enem-mat-3",
    categoria: "enem",
    materia: "Matemática",
    titulo: "🔥 Análise de Gráficos e Tabelas",
    tipo: "videoaula",
    descricao: "TOP 3 no ENEM! 5-7 questões. Interpretação de dados estatísticos.",
    videoId: "6gpZKL3fvEA",
    duracao: 12,
  },
  {
    id: "enem-mat-4",
    categoria: "enem",
    materia: "Matemática",
    titulo: "🔥 Regra de Três e Proporção",
    tipo: "videoaula",
    descricao: "TOP 4 no ENEM! 5-6 questões. Simples, composta, grandezas proporcionais.",
    videoId: "bQUbFCnXA-I",
    duracao: 15,
  },
  // 🟡 PRIORIDADE MÉDIA (11-16 questões)
  {
    id: "enem-mat-5",
    categoria: "enem",
    materia: "Matemática",
    titulo: "Funções de 1º e 2º Grau",
    tipo: "videoaula",
    descricao: "4-6 questões. Função afim, quadrática, gráficos.",
    videoId: "NPUPQ8VaZ8E",
    duracao: 18,
  },
  {
    id: "enem-mat-6",
    categoria: "enem",
    materia: "Matemática",
    titulo: "Geometria Espacial - Volumes",
    tipo: "videoaula",
    descricao: "4-5 questões. Cubo, paralelepípedo, cilindro, cone, pirâmide.",
    videoId: "J91pp9WL77s",
    duracao: 16,
  },
  {
    id: "enem-mat-7",
    categoria: "enem",
    materia: "Matemática",
    titulo: "Estatística Básica",
    tipo: "videoaula",
    descricao: "3-4 questões. Média, mediana, moda, desvio padrão.",
    videoId: "-3z9VTnWZ4Q",
    duracao: 14,
  },
  // 🟢 PRIORIDADE BAIXA - Complementar (7-10 questões)
  {
    id: "enem-mat-8",
    categoria: "enem",
    materia: "Matemática",
    titulo: "Probabilidade",
    tipo: "videoaula",
    descricao: "3-4 questões. Eventos simples e compostos.",
    videoId: "-q-nHpRHeOw",
    duracao: 12,
  },
  {
    id: "enem-mat-9",
    categoria: "enem",
    materia: "Matemática",
    titulo: "Trigonometria Básica",
    tipo: "videoaula",
    descricao: "2-3 questões. Seno, cosseno, tangente, círculo trigonométrico.",
    videoId: "1SDx6I8G114",
    duracao: 15,
  },
  {
    id: "enem-mat-10",
    categoria: "enem",
    materia: "Matemática",
    titulo: "Análise Combinatória",
    tipo: "videoaula",
    descricao: "2-3 questões. Permutação, arranjo, combinação.",
    videoId: "6gpZKL3fvEA",
    duracao: 13,
  },
  
  // Linguagens (Português) - Ordenado por PRIORIDADE (baseado em frequência ENEM 2020-2024)
  // 🔥 PRIORIDADE ALTA - Tópicos que mais caem (24-32 questões)
  {
    id: "enem-ling-1",
    categoria: "enem",
    materia: "Linguagens",
    titulo: "🔥 Interpretação de Texto",
    tipo: "videoaula",
    descricao: "TOP 1 no ENEM! 15-20 questões por prova (33% do Português!). Compreensão global, inferências, contexto.",
    videoId: "QCJ_G6_jAus",
    duracao: 18,
  },
  {
    id: "enem-ling-2",
    categoria: "enem",
    materia: "Linguagens",
    titulo: "🔥 Gêneros Textuais",
    tipo: "videoaula",
    descricao: "TOP 2! 5-7 questões. Notícia, crônica, conto, poema, charge, tirinha, anúncio publicitário.",
    videoId: "FzSsVDKgaXY",
    duracao: 16,
  },
  {
    id: "enem-ling-3",
    categoria: "enem",
    materia: "Linguagens",
    titulo: "🔥 Figuras de Linguagem",
    tipo: "videoaula",
    descricao: "TOP 3! 4-5 questões. Metáfora, comparação, ironia, antítese, hipérbole, eufemismo.",
    videoId: "qk7_8CqUVgE",
    duracao: 15,
  },
  // 🟡 PRIORIDADE MÉDIA (9-13 questões)
  {
    id: "enem-ling-4",
    categoria: "enem",
    materia: "Linguagens",
    titulo: "Funções da Linguagem",
    tipo: "videoaula",
    descricao: "3-4 questões. Referencial, emotiva, conativa, fática, metalinguística, poética.",
    videoId: "1vEtlxjv7fk",
    duracao: 14,
  },
  {
    id: "enem-ling-5",
    categoria: "enem",
    materia: "Linguagens",
    titulo: "Variação Linguística",
    tipo: "videoaula",
    descricao: "2-3 questões. Regional, social, histórica, situacional.",
    videoId: "A-uzDgAIO5k",
    duracao: 13,
  },
  {
    id: "enem-ling-6",
    categoria: "enem",
    materia: "Linguagens",
    titulo: "Intertextualidade",
    tipo: "videoaula",
    descricao: "2-3 questões. Paródia, paráfrase, citação, referências.",
    videoId: "DM9uOh3kbzE",
    duracao: 14,
  },
  {
    id: "enem-ling-7",
    categoria: "enem",
    materia: "Linguagens",
    titulo: "Coesão e Coerência Textual",
    tipo: "videoaula",
    descricao: "2-3 questões. Conectivos, referenciação, progressão textual.",
    videoId: "fRBCpBQIO5A",
    duracao: 15,
  },
  // 🟢 PRIORIDADE BAIXA - Complementar (4-7 questões)
  {
    id: "enem-ling-8",
    categoria: "enem",
    materia: "Linguagens",
    titulo: "Semântica",
    tipo: "videoaula",
    descricao: "2-3 questões. Sinonímia, antonímia, polissemia, homonímia.",
    videoId: "MJOCBHvE52g",
    duracao: 12,
  },
  {
    id: "enem-ling-9",
    categoria: "enem",
    materia: "Linguagens",
    titulo: "Morfologia",
    tipo: "videoaula",
    descricao: "2 questões. Classes gramaticais, formação de palavras.",
    videoId: "QYP0G1sBOz8",
    duracao: 13,
  },
  {
    id: "enem-ling-10",
    categoria: "enem",
    materia: "Linguagens",
    titulo: "Sintaxe",
    tipo: "videoaula",
    descricao: "1-2 questões. Análise sintática, termos da oração.",
    videoId: "tI_JWUNn4Uo",
    duracao: 14,
  },
  
  // ========== FEDERAL ==========
  // Português - Ordenado por PRIORIDADE (baseado em concursos 2020-2024)
  // 🔥 PRIORIDADE ALTA (30-40% das questões de Português)
  {
    id: "fed-port-1",
    categoria: "federal",
    materia: "Português",
    titulo: "🔥 Interpretação de Texto",
    tipo: "videoaula",
    descricao: "TOP 1 em Federais! 30-40% das questões. Compreensão, inferência, intenção do autor.",
    videoId: "fRBCpBQIO5A",
    duracao: 15,
  },
  {
    id: "fed-port-2",
    categoria: "federal",
    materia: "Português",
    titulo: "🔥 Ortografia e Acentuação",
    tipo: "videoaula",
    descricao: "TOP 2! 15-20% das questões. Novo acordo ortográfico, acentos, hífen.",
    videoId: "MJOCBHvE52g",
    duracao: 14,
  },
  {
    id: "fed-port-3",
    categoria: "federal",
    materia: "Português",
    titulo: "🔥 Concordância Verbal e Nominal",
    tipo: "videoaula",
    descricao: "TOP 3! 15-20% das questões. Regras de concordância, casos especiais.",
    videoId: "QYP0G1sBOz8",
    duracao: 16,
  },
  {
    id: "fed-port-4",
    categoria: "federal",
    materia: "Português",
    titulo: "Regência Verbal e Nominal",
    tipo: "videoaula",
    descricao: "10-15% das questões. Principais regências, complementos.",
    videoId: "tI_JWUNn4Uo",
    duracao: 15,
  },
  {
    id: "fed-port-5",
    categoria: "federal",
    materia: "Português",
    titulo: "Crase",
    tipo: "videoaula",
    descricao: "10% das questões. Uso do acento grave, casos obrigatórios e proibidos.",
    videoId: "QCJ_G6_jAus",
    duracao: 13,
  },
  
  // Raciocínio Lógico - Ordenado por PRIORIDADE
  // 🔥 PRIORIDADE ALTA
  {
    id: "fed-rlm-1",
    categoria: "federal",
    materia: "Raciocínio Lógico",
    titulo: "🔥 Lógica de Argumentação",
    tipo: "videoaula",
    descricao: "TOP 1! 30% das questões. Proposições, conectivos lógicos, tabelas-verdade.",
    videoId: "bQUbFCnXA-I",
    duracao: 18,
  },
  {
    id: "fed-rlm-2",
    categoria: "federal",
    materia: "Raciocínio Lógico",
    titulo: "🔥 Problemas com Tabelas e Gráficos",
    tipo: "videoaula",
    descricao: "TOP 2! 25% das questões. Interpretação de dados, análise de informações.",
    videoId: "HK2H-SVycIA",
    duracao: 16,
  },
  {
    id: "fed-rlm-3",
    categoria: "federal",
    materia: "Raciocínio Lógico",
    titulo: "🔥 Sequências Lógicas",
    tipo: "videoaula",
    descricao: "TOP 3! 20% das questões. Padrões numéricos, figuras geométricas, sequências.",
    videoId: "PHdMo7be_uo",
    duracao: 14,
  },
  {
    id: "fed-rlm-4",
    categoria: "federal",
    materia: "Raciocínio Lógico",
    titulo: "Diagramas de Venn",
    tipo: "videoaula",
    descricao: "15% das questões. Conjuntos, interseções, uniões.",
    videoId: "RyvPjAsMLwk",
    duracao: 15,
  },
  {
    id: "fed-rlm-5",
    categoria: "federal",
    materia: "Raciocínio Lógico",
    titulo: "Verdade e Mentira",
    tipo: "videoaula",
    descricao: "10% das questões. Problemas de lógica com afirmações verdadeiras/falsas.",
    videoId: "Voaseu31krA",
    duracao: 13,
  },
  
  // Informática - Ordenado por PRIORIDADE
  // 🔥 PRIORIDADE ALTA
  {
    id: "fed-inf-1",
    categoria: "federal",
    materia: "Informática",
    titulo: "🔥 Windows - Conceitos Básicos",
    tipo: "videoaula",
    descricao: "TOP 1! 25% das questões. Windows 10/11, área de trabalho, arquivos, pastas.",
    videoId: "cWSCZlVJX2Y",
    duracao: 20,
  },
  {
    id: "fed-inf-2",
    categoria: "federal",
    materia: "Informática",
    titulo: "🔥 Microsoft Office (Word e Excel)",
    tipo: "videoaula",
    descricao: "TOP 2! 25% das questões. Formatação, tabelas, fórmulas básicas.",
    videoId: "d5WMTN76S1k",
    duracao: 18,
  },
  {
    id: "fed-inf-3",
    categoria: "federal",
    materia: "Informática",
    titulo: "🔥 Internet e E-mail",
    tipo: "videoaula",
    descricao: "TOP 3! 20% das questões. Navegadores, protocolos (HTTP, HTTPS), e-mail.",
    videoId: "ccyKzXoyjnM",
    duracao: 16,
  },
  {
    id: "fed-inf-4",
    categoria: "federal",
    materia: "Informática",
    titulo: "Segurança da Informação",
    tipo: "videoaula",
    descricao: "20% das questões. Vírus, malware, firewall, antivírus, backup.",
    videoId: "3vjl1cEo07I",
    duracao: 17,
  },
  {
    id: "fed-inf-5",
    categoria: "federal",
    materia: "Informática",
    titulo: "LibreOffice",
    tipo: "videoaula",
    descricao: "10% das questões. Writer, Calc, alternativa gratuita ao Office.",
    videoId: "79cYGI9Aw-w",
    duracao: 15,
  },
  
  // Direito Administrativo - Ordenado por PRIORIDADE
  // 🔥 PRIORIDADE ALTA
  {
    id: "fed-dadm-1",
    categoria: "federal",
    materia: "Direito Administrativo",
    titulo: "🔥 Princípios da Administração Pública",
    tipo: "videoaula",
    descricao: "TOP 1! 30% das questões. LIMPE (Legalidade, Impessoalidade, Moralidade, Publicidade, Eficiência).",
    videoId: "95ARVlEFVWU",
    duracao: 18,
  },
  {
    id: "fed-dadm-2",
    categoria: "federal",
    materia: "Direito Administrativo",
    titulo: "🔥 Poderes Administrativos",
    tipo: "videoaula",
    descricao: "TOP 2! 20% das questões. Vinculado, Discricionário, Hierárquico, Disciplinar, Regulamentar, Polícia.",
    videoId: "BpBvJzQrAs0",
    duracao: 20,
  },
  {
    id: "fed-dadm-3",
    categoria: "federal",
    materia: "Direito Administrativo",
    titulo: "Atos Administrativos",
    tipo: "videoaula",
    descricao: "20% das questões. Conceito, atributos, classificação, anulação e revogação.",
    videoId: "JnAwvdD63Xg",
    duracao: 19,
  },
  {
    id: "fed-dadm-4",
    categoria: "federal",
    materia: "Direito Administrativo",
    titulo: "Licitações (Lei 8.666)",
    tipo: "videoaula",
    descricao: "15% das questões. Modalidades, princípios, fases do procedimento.",
    videoId: "O1rKEY22YQA",
    duracao: 22,
  },
  {
    id: "fed-dadm-5",
    categoria: "federal",
    materia: "Direito Administrativo",
    titulo: "Agentes Públicos",
    tipo: "videoaula",
    descricao: "15% das questões. Servidores públicos, cargos, funções, regime jurídico.",
    videoId: "wnnJSJG1LSk",
    duracao: 17,
  },
  
  // Direito Constitucional - Ordenado por PRIORIDADE
  // 🔥 PRIORIDADE ALTA
  {
    id: "fed-dcon-1",
    categoria: "federal",
    materia: "Direito Constitucional",
    titulo: "🔥 Direitos e Garantias Fundamentais",
    tipo: "videoaula",
    descricao: "TOP 1! 35% das questões. Direitos individuais e coletivos, Habeas Corpus, Mandado de Segurança.",
    videoId: "cWSCZlVJX2Y",
    duracao: 20,
  },
  {
    id: "fed-dcon-2",
    categoria: "federal",
    materia: "Direito Constitucional",
    titulo: "🔥 Poder Legislativo, Executivo e Judiciário",
    tipo: "videoaula",
    descricao: "TOP 2! 25% das questões. Organização, competências, atribuições de cada poder.",
    videoId: "d5WMTN76S1k",
    duracao: 22,
  },
  {
    id: "fed-dcon-3",
    categoria: "federal",
    materia: "Direito Constitucional",
    titulo: "Administração Pública",
    tipo: "videoaula",
    descricao: "20% das questões. Princípios, servidores públicos, licitação.",
    videoId: "ccyKzXoyjnM",
    duracao: 18,
  },
  {
    id: "fed-dcon-4",
    categoria: "federal",
    materia: "Direito Constitucional",
    titulo: "Processo Legislativo",
    tipo: "videoaula",
    descricao: "10% das questões. Leis ordinárias, complementares, emendas constitucionais.",
    videoId: "3vjl1cEo07I",
    duracao: 16,
  },
  {
    id: "fed-dcon-5",
    categoria: "federal",
    materia: "Direito Constitucional",
    titulo: "Ordem Social",
    tipo: "videoaula",
    descricao: "10% das questões. Seguridade social, saúde, educação, cultura.",
    videoId: "79cYGI9Aw-w",
    duracao: 15,
  },
  
  // Direito Administrativo
  {
    id: "fed-dadm-1",
    categoria: "federal",
    materia: "Direito Administrativo",
    titulo: "Princípios da Administração",
    tipo: "videoaula",
    descricao: "LIMPE e outros princípios",
    videoId: "3vjl1cEo07I",
    duracao: 18,
  },
  {
    id: "fed-dadm-2",
    categoria: "federal",
    materia: "Direito Administrativo",
    titulo: "Poderes Administrativos",
    tipo: "videoaula",
    descricao: "Vinculado, discricionário, hierárquico",
    videoId: "79cYGI9Aw-w",
    duracao: 20,
  },
  {
    id: "fed-dadm-3",
    categoria: "federal",
    materia: "Direito Administrativo",
    titulo: "Atos Administrativos",
    tipo: "videoaula",
    descricao: "Conceito e classificação",
    videoId: "95ARVlEFVWU",
    duracao: 22,
  },
  
  // Direito Constitucional
  {
    id: "fed-dcon-1",
    categoria: "federal",
    materia: "Direito Constitucional",
    titulo: "Direitos Fundamentais",
    tipo: "videoaula",
    descricao: "Artigo 5º da CF/88",
    videoId: "BpBvJzQrAs0",
    duracao: 24,
  },
  {
    id: "fed-dcon-2",
    categoria: "federal",
    materia: "Direito Constitucional",
    titulo: "Organização do Estado",
    tipo: "videoaula",
    descricao: "União, Estados e Municípios",
    videoId: "JnAwvdD63Xg",
    duracao: 20,
  },
  {
    id: "fed-dcon-3",
    categoria: "federal",
    materia: "Direito Constitucional",
    titulo: "Poderes da União",
    tipo: "videoaula",
    descricao: "Legislativo, Executivo e Judiciário",
    videoId: "O1rKEY22YQA",
    duracao: 26,
  },
  
  // ========== ESTADUAL ==========
  // Português
  {
    id: "est-port-1",
    categoria: "estadual",
    materia: "Português",
    titulo: "Interpretação de Texto",
    tipo: "videoaula",
    descricao: "Técnicas de interpretação",
    videoId: "tI_JWUNn4Uo",
    duracao: 15,
  },
  {
    id: "est-port-2",
    categoria: "estadual",
    materia: "Português",
    titulo: "Ortografia e Acentuação",
    tipo: "videoaula",
    descricao: "Regras de acentuação",
    videoId: "QCJ_G6_jAus",
    duracao: 14,
  },
  {
    id: "est-port-3",
    categoria: "estadual",
    materia: "Português",
    titulo: "Pontuação",
    tipo: "videoaula",
    descricao: "Uso correto de vírgula e pontos",
    videoId: "FzSsVDKgaXY",
    duracao: 12,
  },
  
  // Matemática
  {
    id: "est-mat-1",
    categoria: "estadual",
    materia: "Matemática",
    titulo: "Regra de Três",
    tipo: "videoaula",
    descricao: "Simples e composta",
    videoId: "RyvPjAsMLwk",
    duracao: 14,
  },
  {
    id: "est-mat-2",
    categoria: "estadual",
    materia: "Matemática",
    titulo: "Equações do 1º Grau",
    tipo: "videoaula",
    descricao: "Resolução de equações lineares",
    videoId: "Voaseu31krA",
    duracao: 12,
  },
  {
    id: "est-mat-3",
    categoria: "estadual",
    materia: "Matemática",
    titulo: "Porcentagem",
    tipo: "videoaula",
    descricao: "Cálculo e aplicações",
    videoId: "GgAo7EqFX9Y",
    duracao: 13,
  },
  
  // Raciocínio Lógico
  {
    id: "est-rlm-1",
    categoria: "estadual",
    materia: "Raciocínio Lógico",
    titulo: "Sequências Lógicas",
    tipo: "videoaula",
    descricao: "Padrões numéricos e de figuras",
    videoId: "v-YLXKoGMbA",
    duracao: 14,
  },
  {
    id: "est-rlm-2",
    categoria: "estadual",
    materia: "Raciocínio Lógico",
    titulo: "Raciocínio Verbal",
    tipo: "videoaula",
    descricao: "Analogias e séries verbais",
    videoId: "2py586t06GM",
    duracao: 12,
  },
  {
    id: "est-rlm-3",
    categoria: "estadual",
    materia: "Raciocínio Lógico",
    titulo: "Problemas Matemáticos",
    tipo: "videoaula",
    descricao: "Resolução de problemas lógicos",
    videoId: "fkGQ_0Ji2_o",
    duracao: 16,
  },
  
  // Conhecimentos Específicos
  {
    id: "est-cesp-1",
    categoria: "estadual",
    materia: "Conhecimentos Específicos",
    titulo: "Legislação Básica",
    tipo: "videoaula",
    descricao: "Estatuto dos servidores",
    videoId: "wnnJSJG1LSk",
    duracao: 20,
  },
  {
    id: "est-cesp-2",
    categoria: "estadual",
    materia: "Conhecimentos Específicos",
    titulo: "Direitos Humanos",
    tipo: "videoaula",
    descricao: "Princípios fundamentais",
    videoId: "cWSCZlVJX2Y",
    duracao: 18,
  },
  {
    id: "est-cesp-3",
    categoria: "estadual",
    materia: "Conhecimentos Específicos",
    titulo: "Ética no Serviço Público",
    tipo: "videoaula",
    descricao: "Código de ética",
    videoId: "d5WMTN76S1k",
    duracao: 16,
  },
  
  // ========== MUNICIPAL ==========
  // Português
  {
    id: "mun-port-1",
    categoria: "municipal",
    materia: "Português",
    titulo: "Classes Gramaticais",
    tipo: "videoaula",
    descricao: "Substantivo, adjetivo, verbo",
    videoId: "qk7_8CqUVgE",
    duracao: 16,
  },
  {
    id: "mun-port-2",
    categoria: "municipal",
    materia: "Português",
    titulo: "Verbos - Tempos e Modos",
    tipo: "videoaula",
    descricao: "Conjugação verbal",
    videoId: "1vEtlxjv7fk",
    duracao: 14,
  },
  {
    id: "mun-port-3",
    categoria: "municipal",
    materia: "Português",
    titulo: "Pronomes",
    tipo: "videoaula",
    descricao: "Tipos e uso correto",
    videoId: "A-uzDgAIO5k",
    duracao: 12,
  },
  
  // Matemática
  {
    id: "mun-mat-1",
    categoria: "municipal",
    materia: "Matemática",
    titulo: "Operações Básicas",
    tipo: "videoaula",
    descricao: "Adição, subtração, multiplicação",
    videoId: "hGkdq9xX5-4",
    duracao: 14,
  },
  {
    id: "mun-mat-2",
    categoria: "municipal",
    materia: "Matemática",
    titulo: "Frações",
    tipo: "videoaula",
    descricao: "Operações com frações",
    videoId: "m7h7v81NBMg",
    duracao: 12,
  },
  {
    id: "mun-mat-3",
    categoria: "municipal",
    materia: "Matemática",
    titulo: "Números Decimais",
    tipo: "videoaula",
    descricao: "Operações e conversões",
    videoId: "n-FiEYAMo3M",
    duracao: 10,
  },
  
  // Conhecimentos Gerais
  {
    id: "mun-cger-1",
    categoria: "municipal",
    materia: "Conhecimentos Gerais",
    titulo: "Atualidades do Brasil",
    tipo: "videoaula",
    descricao: "Política e economia brasileira",
    videoId: "ccyKzXoyjnM",
    duracao: 18,
  },
  {
    id: "mun-cger-2",
    categoria: "municipal",
    materia: "Conhecimentos Gerais",
    titulo: "Geografia do Brasil",
    tipo: "videoaula",
    descricao: "Regiões e características",
    videoId: "3vjl1cEo07I",
    duracao: 16,
  },
  {
    id: "mun-cger-3",
    categoria: "municipal",
    materia: "Conhecimentos Gerais",
    titulo: "História do Brasil",
    tipo: "videoaula",
    descricao: "Principais fatos históricos",
    videoId: "79cYGI9Aw-w",
    duracao: 20,
  },
  
  // Conhecimentos Específicos
  {
    id: "mun-cesp-1",
    categoria: "municipal",
    materia: "Conhecimentos Específicos",
    titulo: "Legislação Municipal",
    tipo: "videoaula",
    descricao: "Lei Orgânica do Município",
    videoId: "95ARVlEFVWU",
    duracao: 20,
  },
  {
    id: "mun-cesp-2",
    categoria: "municipal",
    materia: "Conhecimentos Específicos",
    titulo: "Administração Pública",
    tipo: "videoaula",
    descricao: "Estrutura e funcionamento",
    videoId: "BpBvJzQrAs0",
    duracao: 18,
  },
  {
    id: "mun-cesp-3",
    categoria: "municipal",
    materia: "Conhecimentos Específicos",
    titulo: "Saúde Pública - SUS",
    tipo: "videoaula",
    descricao: "Princípios e diretrizes",
    videoId: "JnAwvdD63Xg",
    duracao: 22,
  },
  
  // ========== TRIBUNAIS ==========
  // Direito Constitucional
  {
    id: "trib-const-1",
    categoria: "tribunais",
    materia: "Direito Constitucional",
    titulo: "Direitos Fundamentais",
    tipo: "videoaula",
    descricao: "CF/88 - Artigo 5º",
    videoId: "O1rKEY22YQA",
    duracao: 24,
  },
  {
    id: "trib-const-2",
    categoria: "tribunais",
    materia: "Direito Constitucional",
    titulo: "Organização do Estado",
    tipo: "videoaula",
    descricao: "União, Estados e Municípios",
    videoId: "wnnJSJG1LSk",
    duracao: 22,
  },
  {
    id: "trib-const-3",
    categoria: "tribunais",
    materia: "Direito Constitucional",
    titulo: "Poder Legislativo",
    tipo: "videoaula",
    descricao: "Estrutura do Congresso",
    videoId: "cWSCZlVJX2Y",
    duracao: 20,
  },
  
  // Direito Administrativo
  {
    id: "trib-adm-1",
    categoria: "tribunais",
    materia: "Direito Administrativo",
    titulo: "Princípios da Administração",
    tipo: "videoaula",
    descricao: "LIMPE e outros princípios",
    videoId: "d5WMTN76S1k",
    duracao: 20,
  },
  {
    id: "trib-adm-2",
    categoria: "tribunais",
    materia: "Direito Administrativo",
    titulo: "Atos Administrativos",
    tipo: "videoaula",
    descricao: "Conceito e atributos",
    videoId: "ccyKzXoyjnM",
    duracao: 22,
  },
  {
    id: "trib-adm-3",
    categoria: "tribunais",
    materia: "Direito Administrativo",
    titulo: "Licitações",
    tipo: "videoaula",
    descricao: "Modalidades de licitação",
    videoId: "3vjl1cEo07I",
    duracao: 26,
  },
  
  // Português
  {
    id: "trib-port-1",
    categoria: "tribunais",
    materia: "Português",
    titulo: "Crase",
    tipo: "videoaula",
    descricao: "Regras de uso da crase",
    videoId: "DM9uOh3kbzE",
    duracao: 14,
  },
  {
    id: "trib-port-2",
    categoria: "tribunais",
    materia: "Português",
    titulo: "Colocação Pronominal",
    tipo: "videoaula",
    descricao: "Próclise, mesóclise e ênclise",
    videoId: "fRBCpBQIO5A",
    duracao: 16,
  },
  {
    id: "trib-port-3",
    categoria: "tribunais",
    materia: "Português",
    titulo: "Vozes Verbais",
    tipo: "videoaula",
    descricao: "Ativa, passiva e reflexiva",
    videoId: "MJOCBHvE52g",
    duracao: 14,
  },
  
  // Raciocínio Lógico
  {
    id: "trib-rlm-1",
    categoria: "tribunais",
    materia: "Raciocínio Lógico",
    titulo: "Lógica de Argumentação",
    tipo: "videoaula",
    descricao: "Silogismos e validade",
    videoId: "pkirFTGTZos",
    duracao: 18,
  },
  {
    id: "trib-rlm-2",
    categoria: "tribunais",
    materia: "Raciocínio Lógico",
    titulo: "Diagramas Lógicos",
    tipo: "videoaula",
    descricao: "Diagramas de Venn e Euler",
    videoId: "UqOzIFDrm8Y",
    duracao: 16,
  },
  {
    id: "trib-rlm-3",
    categoria: "tribunais",
    materia: "Raciocínio Lógico",
    titulo: "Probabilidade",
    tipo: "videoaula",
    descricao: "Cálculo de probabilidades",
    videoId: "NPUPQ8VaZ8E",
    duracao: 18,
  },
  
  // Informática
  {
    id: "trib-inf-1",
    categoria: "tribunais",
    materia: "Informática",
    titulo: "Redes de Computadores",
    tipo: "videoaula",
    descricao: "LAN, WAN, TCP/IP",
    videoId: "79cYGI9Aw-w",
    duracao: 20,
  },
  {
    id: "trib-inf-2",
    categoria: "tribunais",
    materia: "Informática",
    titulo: "Internet e Email",
    tipo: "videoaula",
    descricao: "Navegadores e protocolos",
    videoId: "95ARVlEFVWU",
    duracao: 18,
  },
  {
    id: "trib-inf-3",
    categoria: "tribunais",
    materia: "Informática",
    titulo: "Pacote Office",
    tipo: "videoaula",
    descricao: "Word, Excel e PowerPoint",
    videoId: "BpBvJzQrAs0",
    duracao: 22,
  },
  
  // ========== MILITAR ==========
  // Matemática
  {
    id: "mil-mat-1",
    categoria: "militar",
    materia: "Matemática",
    titulo: "Geometria Plana",
    tipo: "videoaula",
    descricao: "Áreas e perímetros",
    videoId: "J91pp9WL77s",
    duracao: 20,
  },
  {
    id: "mil-mat-2",
    categoria: "militar",
    materia: "Matemática",
    titulo: "Conjuntos Numéricos",
    tipo: "videoaula",
    descricao: "Naturais, inteiros, racionais",
    videoId: "-3z9VTnWZ4Q",
    duracao: 16,
  },
  {
    id: "mil-mat-3",
    categoria: "militar",
    materia: "Matemática",
    titulo: "Funções",
    tipo: "videoaula",
    descricao: "Função afim e quadrática",
    videoId: "-q-nHpRHeOw",
    duracao: 18,
  },
  
  // Física
  {
    id: "mil-fis-1",
    categoria: "militar",
    materia: "Física",
    titulo: "Cinemática - MRU e MRUV",
    tipo: "videoaula",
    descricao: "Movimento retilíneo",
    videoId: "1SDx6I8G114",
    duracao: 18,
  },
  {
    id: "mil-fis-2",
    categoria: "militar",
    materia: "Física",
    titulo: "Leis de Newton",
    tipo: "videoaula",
    descricao: "As três leis do movimento",
    videoId: "6gpZKL3fvEA",
    duracao: 16,
  },
  {
    id: "mil-fis-3",
    categoria: "militar",
    materia: "Física",
    titulo: "Trabalho e Energia",
    tipo: "videoaula",
    descricao: "Energia cinética e potencial",
    videoId: "bQUbFCnXA-I",
    duracao: 18,
  },
  
  // Português
  {
    id: "mil-port-1",
    categoria: "militar",
    materia: "Português",
    titulo: "Orações Subordinadas",
    tipo: "videoaula",
    descricao: "Substantivas, adjetivas, adverbiais",
    videoId: "QYP0G1sBOz8",
    duracao: 18,
  },
  {
    id: "mil-port-2",
    categoria: "militar",
    materia: "Português",
    titulo: "Coesão e Coerência",
    tipo: "videoaula",
    descricao: "Elementos de ligação textual",
    videoId: "tI_JWUNn4Uo",
    duracao: 14,
  },
  {
    id: "mil-port-3",
    categoria: "militar",
    materia: "Português",
    titulo: "Compreensão Textual",
    tipo: "videoaula",
    descricao: "Estratégias de leitura",
    videoId: "QCJ_G6_jAus",
    duracao: 16,
  },
  
  // Química
  {
    id: "mil-qui-1",
    categoria: "militar",
    materia: "Química",
    titulo: "Química Geral",
    tipo: "videoaula",
    descricao: "Átomos e moléculas",
    videoId: "HK2H-SVycIA",
    duracao: 18,
  },
  {
    id: "mil-qui-2",
    categoria: "militar",
    materia: "Química",
    titulo: "Funções Inorgânicas",
    tipo: "videoaula",
    descricao: "Ácidos, bases, sais",
    videoId: "PHdMo7be_uo",
    duracao: 20,
  },
  {
    id: "mil-qui-3",
    categoria: "militar",
    materia: "Química",
    titulo: "Estequiometria",
    tipo: "videoaula",
    descricao: "Cálculos químicos",
    videoId: "RyvPjAsMLwk",
    duracao: 22,
  },
  
  // Inglês
  {
    id: "mil-ing-1",
    categoria: "militar",
    materia: "Inglês",
    titulo: "English Grammar",
    tipo: "videoaula",
    descricao: "Tempos verbais básicos",
    videoId: "JnAwvdD63Xg",
    duracao: 16,
  },
  {
    id: "mil-ing-2",
    categoria: "militar",
    materia: "Inglês",
    titulo: "Reading Comprehension",
    tipo: "videoaula",
    descricao: "Técnicas de leitura",
    videoId: "O1rKEY22YQA",
    duracao: 18,
  },
  {
    id: "mil-ing-3",
    categoria: "militar",
    materia: "Inglês",
    titulo: "Vocabulary",
    tipo: "videoaula",
    descricao: "Vocabulário essencial",
    videoId: "wnnJSJG1LSk",
    duracao: 14,
  },
  
  // História
  {
    id: "mil-his-1",
    categoria: "militar",
    materia: "História",
    titulo: "História do Brasil",
    tipo: "videoaula",
    descricao: "Do colonial à república",
    videoId: "cWSCZlVJX2Y",
    duracao: 20,
  },
  {
    id: "mil-his-2",
    categoria: "militar",
    materia: "História",
    titulo: "Segunda Guerra Mundial",
    tipo: "videoaula",
    descricao: "Causas e consequências",
    videoId: "d5WMTN76S1k",
    duracao: 22,
  },
  {
    id: "mil-his-3",
    categoria: "militar",
    materia: "História",
    titulo: "Guerra Fria",
    tipo: "videoaula",
    descricao: "Bipolarização mundial",
    videoId: "ccyKzXoyjnM",
    duracao: 18,
  },
  
  // Geografia
  {
    id: "mil-geo-1",
    categoria: "militar",
    materia: "Geografia",
    titulo: "Cartografia",
    tipo: "videoaula",
    descricao: "Mapas e coordenadas",
    videoId: "3vjl1cEo07I",
    duracao: 16,
  },
  {
    id: "mil-geo-2",
    categoria: "militar",
    materia: "Geografia",
    titulo: "Geopolítica",
    tipo: "videoaula",
    descricao: "Relações internacionais",
    videoId: "79cYGI9Aw-w",
    duracao: 18,
  },
  {
    id: "mil-geo-3",
    categoria: "militar",
    materia: "Geografia",
    titulo: "Geografia do Brasil",
    tipo: "videoaula",
    descricao: "Aspectos físicos e regionais",
    videoId: "95ARVlEFVWU",
    duracao: 20,
  },
  
  // VESTIBULAR - Matérias adicionais
  // Física
  {
    id: "vest-fis-1",
    categoria: "vestibular",
    materia: "Física",
    titulo: "Cinemática Escalar",
    tipo: "videoaula",
    descricao: "MRU e MRUV",
    videoId: "Voaseu31krA",
    duracao: 18,
  },
  {
    id: "vest-fis-2",
    categoria: "vestibular",
    materia: "Física",
    titulo: "Dinâmica - Leis de Newton",
    tipo: "videoaula",
    descricao: "As três leis do movimento",
    videoId: "GgAo7EqFX9Y",
    duracao: 16,
  },
  {
    id: "vest-fis-3",
    categoria: "vestibular",
    materia: "Física",
    titulo: "Óptica Geométrica",
    tipo: "videoaula",
    descricao: "Reflexão e refração",
    videoId: "v-YLXKoGMbA",
    duracao: 20,
  },
  
  // Química
  {
    id: "vest-qui-1",
    categoria: "vestibular",
    materia: "Química",
    titulo: "Tabela Periódica",
    tipo: "videoaula",
    descricao: "Propriedades periódicas",
    videoId: "2py586t06GM",
    duracao: 16,
  },
  {
    id: "vest-qui-2",
    categoria: "vestibular",
    materia: "Química",
    titulo: "Ligações Químicas",
    tipo: "videoaula",
    descricao: "Iônica, covalente, metálica",
    videoId: "fkGQ_0Ji2_o",
    duracao: 18,
  },
  {
    id: "vest-qui-3",
    categoria: "vestibular",
    materia: "Química",
    titulo: "Estequiometria",
    tipo: "videoaula",
    descricao: "Cálculos químicos",
    videoId: "hGkdq9xX5-4",
    duracao: 22,
  },
  
  // Biologia
  {
    id: "vest-bio-1",
    categoria: "vestibular",
    materia: "Biologia",
    titulo: "Citologia",
    tipo: "videoaula",
    descricao: "Estrutura celular",
    videoId: "BpBvJzQrAs0",
    duracao: 20,
  },
  {
    id: "vest-bio-2",
    categoria: "vestibular",
    materia: "Biologia",
    titulo: "Genética - Leis de Mendel",
    tipo: "videoaula",
    descricao: "Primeira e segunda lei",
    videoId: "JnAwvdD63Xg",
    duracao: 18,
  },
  {
    id: "vest-bio-3",
    categoria: "vestibular",
    materia: "Biologia",
    titulo: "Ecologia",
    tipo: "videoaula",
    descricao: "Relações ecológicas",
    videoId: "O1rKEY22YQA",
    duracao: 16,
  },
  
  // História
  {
    id: "vest-his-1",
    categoria: "vestibular",
    materia: "História",
    titulo: "Brasil Colonial",
    tipo: "videoaula",
    descricao: "Colonização portuguesa",
    videoId: "wnnJSJG1LSk",
    duracao: 20,
  },
  {
    id: "vest-his-2",
    categoria: "vestibular",
    materia: "História",
    titulo: "Revolução Francesa",
    tipo: "videoaula",
    descricao: "Causas e consequências",
    videoId: "cWSCZlVJX2Y",
    duracao: 18,
  },
  {
    id: "vest-his-3",
    categoria: "vestibular",
    materia: "História",
    titulo: "Segunda Guerra Mundial",
    tipo: "videoaula",
    descricao: "Desenvolvimento e consequências",
    videoId: "d5WMTN76S1k",
    duracao: 25,
  },
  
  // Geografia
  {
    id: "vest-geo-1",
    categoria: "vestibular",
    materia: "Geografia",
    titulo: "Geologia e Relevo",
    tipo: "videoaula",
    descricao: "Estrutura da Terra",
    videoId: "ccyKzXoyjnM",
    duracao: 16,
  },
  {
    id: "vest-geo-2",
    categoria: "vestibular",
    materia: "Geografia",
    titulo: "Clima e Vegetação",
    tipo: "videoaula",
    descricao: "Climas do Brasil",
    videoId: "3vjl1cEo07I",
    duracao: 18,
  },
  {
    id: "vest-geo-3",
    categoria: "vestibular",
    materia: "Geografia",
    titulo: "Urbanização",
    tipo: "videoaula",
    descricao: "Processo urbano brasileiro",
    videoId: "79cYGI9Aw-w",
    duracao: 20,
  },
  
  // Inglês
  {
    id: "vest-ing-1",
    categoria: "vestibular",
    materia: "Inglês",
    titulo: "Reading Comprehension",
    tipo: "videoaula",
    descricao: "Técnicas de leitura",
    videoId: "95ARVlEFVWU",
    duracao: 15,
  },
  {
    id: "vest-ing-2",
    categoria: "vestibular",
    materia: "Inglês",
    titulo: "Grammar - Verb Tenses",
    tipo: "videoaula",
    descricao: "Tempos verbais",
    videoId: "BpBvJzQrAs0",
    duracao: 18,
  },
  {
    id: "vest-ing-3",
    categoria: "vestibular",
    materia: "Inglês",
    titulo: "Vocabulário FUVEST",
    tipo: "videoaula",
    descricao: "Palavras mais cobradas",
    videoId: "JnAwvdD63Xg",
    duracao: 12,
  },
  
  // ENEM - Matérias adicionais
  // Ciências Humanas - Ordenado por PRIORIDADE (História + Geografia)
  // 🔥 HISTÓRIA - Tópicos prioritários (30 Brasil + 15 Geral = 45 questões)
  {
    id: "enem-hum-1",
    categoria: "enem",
    materia: "Ciências Humanas",
    titulo: "🔥 HISTÓRIA: República Brasileira",
    tipo: "videoaula",
    descricao: "TOP 1 História! 8-10 questões. Era Vargas, Ditadura Militar (1964-1985), Redemocratização, Nova República.",
    videoId: "O1rKEY22YQA",
    duracao: 18,
  },
  {
    id: "enem-hum-2",
    categoria: "enem",
    materia: "Ciências Humanas",
    titulo: "🔥 HISTÓRIA: Brasil Colônia",
    tipo: "videoaula",
    descricao: "TOP 2 História! 5-6 questões. Ciclos econômicos (açúcar, ouro), Escravidão africana, Administração colonial.",
    videoId: "wnnJSJG1LSk",
    duracao: 16,
  },
  {
    id: "enem-hum-3",
    categoria: "enem",
    materia: "Ciências Humanas",
    titulo: "🔥 HISTÓRIA: 2ª Guerra Mundial e Guerra Fria",
    tipo: "videoaula",
    descricao: "TOP 3 História! 4-5 questões. Nazismo, Fascismo, Holocausto, Bipolarização mundial (EUA vs URSS).",
    videoId: "cWSCZlVJX2Y",
    duracao: 18,
  },
  {
    id: "enem-hum-4",
    categoria: "enem",
    materia: "Ciências Humanas",
    titulo: "HISTÓRIA: Movimentos Sociais no Brasil",
    tipo: "videoaula",
    descricao: "3-4 questões. Abolicionismo, Trabalhista, MST, Movimento Negro, Feminismo.",
    videoId: "d5WMTN76S1k",
    duracao: 15,
  },
  {
    id: "enem-hum-5",
    categoria: "enem",
    materia: "Ciências Humanas",
    titulo: "HISTÓRIA: Império Brasileiro",
    tipo: "videoaula",
    descricao: "3-4 questões. D. Pedro I, D. Pedro II, Crise do Império, Abolição.",
    videoId: "ccyKzXoyjnM",
    duracao: 16,
  },
  {
    id: "enem-hum-6",
    categoria: "enem",
    materia: "Ciências Humanas",
    titulo: "HISTÓRIA: Revolução Industrial",
    tipo: "videoaula",
    descricao: "2-3 questões. Primeira e Segunda revolução, Transformações sociais, Capitalismo.",
    videoId: "3vjl1cEo07I",
    duracao: 14,
  },
  // 🔥 GEOGRAFIA - Tópicos prioritários (45 questões)
  {
    id: "enem-hum-7",
    categoria: "enem",
    materia: "Ciências Humanas",
    titulo: "🔥 GEOGRAFIA: Geografia Urbana",
    tipo: "videoaula",
    descricao: "TOP 1 Geografia! 7-8 questões. Urbanização brasileira, Problemas urbanos (mobilidade, violência, moradia).",
    videoId: "79cYGI9Aw-w",
    duracao: 17,
  },
  {
    id: "enem-hum-8",
    categoria: "enem",
    materia: "Ciências Humanas",
    titulo: "🔥 GEOGRAFIA: Meio Ambiente e Sustentabilidade",
    tipo: "videoaula",
    descricao: "TOP 2 Geografia! 6-7 questões. Biomas brasileiros, Desmatamento, Mudanças climáticas.",
    videoId: "95ARVlEFVWU",
    duracao: 18,
  },
  {
    id: "enem-hum-9",
    categoria: "enem",
    materia: "Ciências Humanas",
    titulo: "🔥 GEOGRAFIA: Climatologia",
    tipo: "videoaula",
    descricao: "TOP 3 Geografia! 5-6 questões. Climas do Brasil, Fatores climáticos, Fenômenos atmosféricos.",
    videoId: "BpBvJzQrAs0",
    duracao: 16,
  },
  {
    id: "enem-hum-10",
    categoria: "enem",
    materia: "Ciências Humanas",
    titulo: "GEOGRAFIA: Geopolítica Mundial",
    tipo: "videoaula",
    descricao: "4-5 questões. Conflitos internacionais, Globalização, Blocos econômicos.",
    videoId: "JnAwvdD63Xg",
    duracao: 17,
  },
  {
    id: "enem-hum-11",
    categoria: "enem",
    materia: "Ciências Humanas",
    titulo: "GEOGRAFIA: Demografia",
    tipo: "videoaula",
    descricao: "4-5 questões. População brasileira, Migrações, Pirâmides etárias.",
    videoId: "O1rKEY22YQA",
    duracao: 15,
  },
  {
    id: "enem-hum-12",
    categoria: "enem",
    materia: "Ciências Humanas",
    titulo: "GEOGRAFIA: Cartografia",
    tipo: "videoaula",
    descricao: "3-4 questões. Mapas, Escalas, Projeções cartográficas.",
    videoId: "wnnJSJG1LSk",
    duracao: 14,
  },
  {
    id: "enem-hum-13",
    categoria: "enem",
    materia: "Ciências Humanas",
    titulo: "GEOGRAFIA: Agricultura Brasileira",
    tipo: "videoaula",
    descricao: "3-4 questões. Agronegócio, Reforma agrária, Agricultura familiar.",
    videoId: "cWSCZlVJX2Y",
    duracao: 16,
  },
  
  {
    id: "enem-nat-1",
    categoria: "enem",
    materia: "Ciências da Natureza",
    titulo: "🔥 BIOLOGIA: Ecologia e Meio Ambiente",
    tipo: "videoaula",
    descricao: "TOP 1 Biologia! 8-10 questões. Cadeias alimentares, ciclos biogeoquímicos, poluição, sucessão ecológica.",
    videoId: "d5WMTN76S1k",
    duracao: 15,
  },
  {
    id: "enem-nat-2",
    categoria: "enem",
    materia: "Ciências da Natureza",
    titulo: "🔥 FÍSICA: Mecânica",
    tipo: "videoaula",
    descricao: "TOP 1 Física! 10-12 questões. Cinemática (MRU, MRUV), Leis de Newton, Energia mecânica, Trabalho.",
    videoId: "ccyKzXoyjnM",
    duracao: 20,
  },
  {
    id: "enem-nat-3",
    categoria: "enem",
    materia: "Ciências da Natureza",
    titulo: "🔥 FÍSICA: Eletricidade",
    tipo: "videoaula",
    descricao: "TOP 2 Física! 8-9 questões. Circuitos elétricos, Lei de Ohm, Potência elétrica, Consumo de energia.",
    videoId: "3vjl1cEo07I",
    duracao: 17,
  },
  {
    id: "enem-nat-4",
    categoria: "enem",
    materia: "Ciências da Natureza",
    titulo: "🔥 QUÍMICA: Química Ambiental",
    tipo: "videoaula",
    descricao: "TOP 1 Química! 6-7 questões. Poluição, Efeito estufa, Chuva ácida, Aquecimento global.",
    videoId: "79cYGI9Aw-w",
    duracao: 18,
  },
  {
    id: "enem-nat-5",
    categoria: "enem",
    materia: "Ciências da Natureza",
    titulo: "🔥 BIOLOGIA: Citologia",
    tipo: "videoaula",
    descricao: "TOP 2 Biologia! 5-6 questões. Células procariotas/eucariotas, Organelas, Respiração celular.",
    videoId: "95ARVlEFVWU",
    duracao: 16,
  },
  {
    id: "enem-nat-6",
    categoria: "enem",
    materia: "Ciências da Natureza",
    titulo: "🔥 BIOLOGIA: Genética",
    tipo: "videoaula",
    descricao: "TOP 3 Biologia! 5-6 questões. Leis de Mendel, Heredogramas, Grupos sanguíneos.",
    videoId: "BpBvJzQrAs0",
    duracao: 17,
  },
  {
    id: "enem-nat-7",
    categoria: "enem",
    materia: "Ciências da Natureza",
    titulo: "🔥 FÍSICA: Ondulatória",
    tipo: "videoaula",
    descricao: "TOP 3 Física! 6-7 questões. Ondas sonoras e eletromagnéticas, Características das ondas.",
    videoId: "JnAwvdD63Xg",
    duracao: 15,
  },
  {
    id: "enem-nat-8",
    categoria: "enem",
    materia: "Ciências da Natureza",
    titulo: "🔥 QUÍMICA: Estequiometria",
    tipo: "videoaula",
    descricao: "TOP 2 Química! 5-6 questões. Cálculos químicos, Rendimento de reações, Reagente limitante.",
    videoId: "O1rKEY22YQA",
    duracao: 19,
  },
  {
    id: "enem-nat-9",
    categoria: "enem",
    materia: "Ciências da Natureza",
    titulo: "BIOLOGIA: Evolução",
    tipo: "videoaula",
    descricao: "4-5 questões. Darwin, Seleção natural, Especiação.",
    videoId: "wnnJSJG1LSk",
    duracao: 14,
  },
  {
    id: "enem-nat-10",
    categoria: "enem",
    materia: "Ciências da Natureza",
    titulo: "BIOLOGIA: Fisiologia Humana",
    tipo: "videoaula",
    descricao: "4-5 questões. Sistemas do corpo (digestório, circulatório, respiratório).",
    videoId: "cWSCZlVJX2Y",
    duracao: 16,
  },
  {
    id: "enem-nat-11",
    categoria: "enem",
    materia: "Ciências da Natureza",
    titulo: "QUÍMICA: Eletroquímica",
    tipo: "videoaula",
    descricao: "4-5 questões. Pilhas, Baterias, Eletrólise, Corrosão.",
    videoId: "ccyKzXoyjnM",
    duracao: 17,
  },
  {
    id: "enem-nat-12",
    categoria: "enem",
    materia: "Ciências da Natureza",
    titulo: "QUÍMICA: Química Orgânica",
    tipo: "videoaula",
    descricao: "4-5 questões. Funções orgânicas, Nomenclatura, Isomeria.",
    videoId: "3vjl1cEo07I",
    duracao: 18,
  },
  {
    id: "enem-nat-13",
    categoria: "enem",
    materia: "Ciências da Natureza",
    titulo: "FÍSICA: Óptica",
    tipo: "videoaula",
    descricao: "4-5 questões. Espelhos, Lentes, Refração da luz.",
    videoId: "79cYGI9Aw-w",
    duracao: 14,
  },
  {
    id: "enem-nat-14",
    categoria: "enem",
    materia: "Ciências da Natureza",
    titulo: "FÍSICA: Termologia",
    tipo: "videoaula",
    descricao: "4-5 questões. Calor, Temperatura, Dilatação térmica.",
    videoId: "95ARVlEFVWU",
    duracao: 15,
  },
  {
    id: "enem-nat-15",
    categoria: "enem",
    materia: "Ciências da Natureza",
    titulo: "BIOLOGIA: Botânica",
    tipo: "videoaula",
    descricao: "3-4 questões. Fotossíntese, Partes das plantas, Classificação.",
    videoId: "BpBvJzQrAs0",
    duracao: 13,
  },
  
  {
    id: "enem-ling-1",
    categoria: "enem",
    materia: "Linguagens",
    titulo: "Funções da Linguagem",
    tipo: "videoaula",
    descricao: "Seis funções comunicativas",
    videoId: "79cYGI9Aw-w",
    duracao: 14,
  },
  {
    id: "enem-ling-2",
    categoria: "enem",
    materia: "Linguagens",
    titulo: "Gêneros Textuais",
    tipo: "videoaula",
    descricao: "Carta, artigo, crônica",
    videoId: "95ARVlEFVWU",
    duracao: 12,
  },
  {
    id: "enem-ling-3",
    categoria: "enem",
    materia: "Linguagens",
    titulo: "Interpretação de Imagens",
    tipo: "videoaula",
    descricao: "Charges e infográficos",
    videoId: "BpBvJzQrAs0",
    duracao: 10,
  },
];

// Helper function para buscar materiais por categoria e matéria
export function getMaterialsPorCategoriaMateria(
  categoria: CategoriaConcurso,
  materia: string,
  tipo?: TipoMaterial
): MaterialConcurso[] {
  return concursosData.filter(
    (material) =>
      material.categoria === categoria &&
      material.materia === materia &&
      (!tipo || material.tipo === tipo)
  );
}

// Helper function para buscar todas as matérias de uma categoria
export function getMateriasPorCategoria(categoria: CategoriaConcurso): string[] {
  const materias = new Set<string>();
  concursosData.forEach((material) => {
    if (material.categoria === categoria) {
      materias.add(material.materia);
    }
  });
  return Array.from(materias);
}
