import { SubjectGrade } from "./types";

const SUBJECT_INFO = {
  matematica: {
    name: "Matemática",
    description: "Álgebra, geometria, estatística e mais",
    icon: "📐",
  },
  portugues: {
    name: "Português",
    description: "Literatura, gramática e interpretação",
    icon: "📖",
  },
  historia: {
    name: "História",
    description: "História do Brasil e do mundo",
    icon: "🏛️",
  },
  geografia: {
    name: "Geografia",
    description: "Clima, continentes e demografia",
    icon: "🌍",
  },
  ciencias: {
    name: "Ciências",
    description: "Biologia, física, química e natureza",
    icon: "🔬",
  },
  ingles: {
    name: "Inglês",
    description: "Vocabulário e gramática inglesa",
    icon: "🌐",
  },
};

export const data: SubjectGrade[] = [
  // Matemática - 6º ano
  {
    subject: "matematica",
    grade: "6º ano",
    lessons: [
      {
        id: "mat-6-1",
        title: "Adição e Subtração",
        description: "Operações fundamentais com Professor Ferretto",
        videoId: "e78_5WIssSU",
        duration: 15,
      },
      {
        id: "mat-6-2",
        title: "Multiplicação e Divisão",
        description: "Operações com números inteiros e decimais",
        videoId: "0UGJRHq2PS4",
        duration: 18,
      },
      {
        id: "mat-6-3",
        title: "Expressões Numéricas",
        description: "Ordem nas operações matemáticas",
        videoId: "BhDm2qGy780",
        duration: 16,
      },
      {
        id: "mat-6-4",
        title: "Frações - Parte 1",
        description: "Notação e propriedades das frações",
        videoId: "YJyY6A_MOQc",
        duration: 20,
      },
      {
        id: "mat-6-5",
        title: "Frações - Parte 2",
        description: "Operações básicas com frações",
        videoId: "SgJpB78R7x0",
        duration: 22,
      },
      {
        id: "mat-6-6",
        title: "Potenciação",
        description: "Definição e propriedades de potências",
        videoId: "4Vfw1XiHTpM",
        duration: 18,
      },
      {
        id: "mat-6-7",
        title: "Radiciação",
        description: "Raiz quadrada, definição e propriedades",
        videoId: "QmIjZgKhAEo",
        duration: 17,
      },
    ],
    quizzes: [
      {
        id: "quiz-mat-6-1",
        lessonId: "mat-6-1",
        question: "Qual é o resultado de 15 + 8?",
        options: ["20", "23", "25", "28"],
        correctAnswer: 1,
        explanation: "15 + 8 = 23. Somando 15 com 8 obtemos 23.",
      },
      {
        id: "quiz-mat-6-2",
        lessonId: "mat-6-1",
        question: "Quanto é 7 × 6?",
        options: ["35", "40", "42", "48"],
        correctAnswer: 2,
        explanation: "7 × 6 = 42. Essa é uma operação de multiplicação básica.",
      },
      {
        id: "quiz-mat-6-3",
        lessonId: "mat-6-2",
        question: "Se você divide uma pizza em 4 partes iguais e come 1 parte, que fração você comeu?",
        options: ["1/2", "1/3", "1/4", "1/5"],
        correctAnswer: 2,
        explanation: "Se você comeu 1 de 4 partes, você comeu 1/4 da pizza.",
      },
      {
        id: "quiz-mat-6-4",
        lessonId: "mat-6-3",
        question: "Qual é o nome da forma geométrica com 4 lados iguais?",
        options: ["Triângulo", "Quadrado", "Pentágono", "Círculo"],
        correctAnswer: 1,
        explanation: "O quadrado é a forma com 4 lados iguais e 4 ângulos retos.",
      },
    ],
  },
  // Português - 6º ano
  {
    subject: "portugues",
    grade: "6º ano",
    lessons: [
      {
        id: "port-6-1",
        title: "Análise Sintática",
        description: "Aprenda análise sintática",
        videoId: "_1n0nhz4miQ",
        duration: 13,
      },
      {
        id: "port-6-2",
        title: "Verbos",
        description: "Aprenda sobre verbos com Eduardo Gafa",
        videoId: "PDB-6uA2OE8",
        duration: 15,
      },
      {
        id: "port-6-3",
        title: "Literatura",
        description: "Aprenda sobre literatura",
        videoId: "alAXSk8ly-o",
        duration: 9,
      },
      {
        id: "port-6-4",
        title: "Substantivos",
        description: "Conceito e tipos de substantivos",
        videoId: "8iXiBgCnGv4",
        duration: 11,
      },
      {
        id: "port-6-5",
        title: "Pronomes",
        description: "Pronomes e suas aplicações em textos",
        videoId: "cZ3MmXT0uys",
        duration: 10,
      },
    ],
    quizzes: [
      {
        id: "quiz-port-6-1",
        lessonId: "port-6-1",
        question: "Qual é a principal função da leitura?",
        options: [
          "Fazer barulho",
          "Compreender e adquirir conhecimento",
          "Passar tempo",
          "Nenhuma das anteriores",
        ],
        correctAnswer: 1,
        explanation:
          "A leitura nos ajuda a compreender o texto e adquirir novos conhecimentos.",
      },
      {
        id: "quiz-port-6-2",
        lessonId: "port-6-2",
        question: "Qual é a classe de palavras que nomeia seres e coisas?",
        options: ["Adjetivo", "Substantivo", "Verbo", "Advérbio"],
        correctAnswer: 1,
        explanation:
          "Substantivo é a classe de palavras que nomeia seres, coisas, sentimentos, etc.",
      },
      {
        id: "quiz-port-6-3",
        lessonId: "port-6-2",
        question: "Na frase 'O carro vermelho é lindo', qual palavra é um adjetivo?",
        options: ["carro", "vermelho", "lindo", "é"],
        correctAnswer: 1,
        explanation:
          "Tanto 'vermelho' quanto 'lindo' são adjetivos, mas entre as opções, consideramos 'vermelho'.",
      },
      {
        id: "quiz-port-6-4",
        lessonId: "port-6-3",
        question: "Qual sinal de pontuação indica o fim de uma frase?",
        options: ["Vírgula", "Ponto", "Ponto e vírgula", "Dois pontos"],
        correctAnswer: 1,
        explanation: "O ponto (.) é usado para marcar o fim de uma frase.",
      },
    ],
  },
  // História - 6º ano
  {
    subject: "historia",
    grade: "6º ano",
    lessons: [
      {
        id: "hist-6-1",
        title: "Descobrimento do Brasil",
        description: "A chegada de Pedro Álvares Cabral em 1500",
        videoId: "zDubU-9Td4I",
        duration: 15,
      },
      {
        id: "hist-6-2",
        title: "Colonização Portuguesa",
        description: "Como os portugueses colonizaram o Brasil",
        videoId: "3pCaIDAY-0E",
        duration: 14,
      },
      {
        id: "hist-6-3",
        title: "Povos Indígenas",
        description: "As civilizações indígenas antes da colonização",
        videoId: "wyGdwbxnIEk",
        duration: 13,
      },
      {
        id: "hist-6-4",
        title: "Escravidão no Brasil",
        description: "História da escravidão africana no Brasil",
        videoId: "Yp9Je_uQ6BY",
        duration: 16,
      },
    ],
    quizzes: [
      {
        id: "quiz-hist-6-1",
        lessonId: "hist-6-1",
        question: "Em que ano Pedro Álvares Cabral chegou ao Brasil?",
        options: ["1400", "1450", "1500", "1550"],
        correctAnswer: 2,
        explanation: "Pedro Álvares Cabral chegou ao Brasil em 22 de abril de 1500.",
      },
      {
        id: "quiz-hist-6-2",
        lessonId: "hist-6-1",
        question: "Qual país colonizou o Brasil?",
        options: ["Espanha", "Inglaterra", "França", "Portugal"],
        correctAnswer: 3,
        explanation: "Portugal foi o país que colonizou o Brasil.",
      },
      {
        id: "quiz-hist-6-3",
        lessonId: "hist-6-2",
        question: "Qual era o objetivo principal da colonização portuguesa no Brasil?",
        options: [
          "Exploração de recursos naturais",
          "Paz com indígenas",
          "Pesquisa científica",
          "Turismo",
        ],
        correctAnswer: 0,
        explanation:
          "Os portugueses vieram explorar recursos naturais como ouro, madeira e açúcar.",
      },
      {
        id: "quiz-hist-6-4",
        lessonId: "hist-6-3",
        question: "Qual povo indígena era importante no território que se tornou São Paulo?",
        options: ["Tupis", "Guaranis", "Potiguares", "Tamoios"],
        correctAnswer: 0,
        explanation: "Os Tupis eram um povo indígena importante na região de São Paulo.",
      },
    ],
  },
  // Geografia - 6º ano
  {
    subject: "geografia",
    grade: "6º ano",
    lessons: [
      {
        id: "geog-6-1",
        title: "Continentes e Oceanos",
        description: "Localização dos continentes e oceanos no globo terrestre",
        videoId: "Z8cVL_5WUYQ",
        duration: 12,
      },
      {
        id: "geog-6-2",
        title: "Clima do Brasil",
        description: "Os diferentes tipos de clima do Brasil",
        videoId: "wXCRF4NC4o8",
        duration: 14,
      },
      {
        id: "geog-6-3",
        title: "Biomas Brasileiros",
        description: "Amazônia, Cerrado, Caatinga e outros biomas",
        videoId: "GdsGVgULosE",
        duration: 13,
      },
      {
        id: "geog-6-4",
        title: "Vegetação e Relevo",
        description: "Tipos de vegetação e relevo do Brasil",
        videoId: "ryd04x5x_NE",
        duration: 15,
      },
      {
        id: "geog-6-5",
        title: "Cartografia",
        description: "Leitura e interpretação de mapas",
        videoId: "Ai_1DGZjHW0",
        duration: 11,
      },
    ],
    quizzes: [
      {
        id: "quiz-geog-6-1",
        lessonId: "geog-6-1",
        question: "Quantos continentes existem?",
        options: ["5", "6", "7", "8"],
        correctAnswer: 2,
        explanation: "Existem 7 continentes: América, Europa, Ásia, África, Oceania, Antártida e Antártica.",
      },
      {
        id: "quiz-geog-6-2",
        lessonId: "geog-6-1",
        question: "Qual é o maior oceano do planeta?",
        options: ["Atlântico", "Índico", "Pacífico", "Ártico"],
        correctAnswer: 2,
        explanation: "O Oceano Pacífico é o maior oceano da Terra.",
      },
      {
        id: "quiz-geog-6-3",
        lessonId: "geog-6-2",
        question: "Qual é o clima predominante na maior parte do Brasil?",
        options: ["Desértico", "Tropical e Subtropical", "Polar", "Temperado"],
        correctAnswer: 1,
        explanation: "O Brasil possui principalmente clima tropical e subtropical.",
      },
      {
        id: "quiz-geog-6-4",
        lessonId: "geog-6-3",
        question: "Qual é o maior bioma do Brasil?",
        options: ["Cerrado", "Caatinga", "Amazônia", "Mata Atlântica"],
        correctAnswer: 2,
        explanation: "A Amazônia é o maior bioma do Brasil, cobrindo aproximadamente 60% do território.",
      },
    ],
  },
  // Inglês - 6º ano
  {
    subject: "ingles",
    grade: "6º ano",
    lessons: [
      {
        id: "eng-6-1",
        title: "Hello World - Saudações",
        description: "Aprender a saudar em inglês",
        videoId: "AE3cwqdqXBc",
        duration: 8,
      },
      {
        id: "eng-6-2",
        title: "Numbers 1-100",
        description: "Números em inglês de 1 a 100",
        videoId: "_fmAYE-T0hg",
        duration: 10,
      },
      {
        id: "eng-6-3",
        title: "Family Members",
        description: "Membros da família em inglês",
        videoId: "m6eF1af6LqA",
        duration: 12,
      },
      {
        id: "eng-6-4",
        title: "Verbo To Be",
        description: "O verbo 'to be' e suas conjugações",
        videoId: "2Wig3XCO_cs",
        duration: 11,
      },
    ],
    quizzes: [
      {
        id: "quiz-eng-6-1",
        lessonId: "eng-6-1",
        question: "Como se diz 'Olá' em inglês?",
        options: ["Goodbye", "Hello", "Thank you", "Sorry"],
        correctAnswer: 1,
        explanation: "'Hello' significa 'Olá' em inglês.",
      },
      {
        id: "quiz-eng-6-2",
        lessonId: "eng-6-1",
        question: "Como se diz 'Tudo bem?' em inglês?",
        options: ["How are you?", "Who are you?", "Where are you?", "What are you?"],
        correctAnswer: 0,
        explanation: "'How are you?' significa 'Tudo bem?' ou 'Como você está?'",
      },
      {
        id: "quiz-eng-6-3",
        lessonId: "eng-6-2",
        question: "Qual é o número 10 em inglês?",
        options: ["Seven", "Eight", "Nine", "Ten"],
        correctAnswer: 3,
        explanation: "'Ten' é o número 10 em inglês.",
      },
      {
        id: "quiz-eng-6-4",
        lessonId: "eng-6-3",
        question: "Como se diz 'mãe' em inglês?",
        options: ["Father", "Mother", "Sister", "Brother"],
        correctAnswer: 1,
        explanation: "'Mother' significa 'mãe' em inglês.",
      },
    ],
  },

  // 7º ano - Matemática
  {
    subject: "matematica",
    grade: "7º ano",
    lessons: [
      {
        id: "mat-7-1",
        title: "Números Inteiros",
        description: "Números positivos, negativos e suas operações - Canal Futura",
        videoId: "1T8j0CTPYps",
        duration: 14,
      },
      {
        id: "mat-7-2",
        title: "Álgebra Básica",
        description: "Expressões algébricas e resolução de equações - Canal Futura",
        videoId: "ow3Gux4ChYM",
        duration: 16,
      },
      {
        id: "mat-7-3",
        title: "Proporção e Razão",
        description: "Entender proporções e aplicar em problemas",
        videoId: "224Xkc0MX64",
        duration: 13,
      },
      {
        id: "mat-7-4",
        title: "Equações do 1º Grau",
        description: "Resolvendo equações do primeiro grau",
        videoId: "KDkSjIBrups",
        duration: 15,
      },
      {
        id: "mat-7-5",
        title: "Porcentagem",
        description: "Cálculo de porcentagens e aplicações práticas",
        videoId: "WDIHtdD7XJo",
        duration: 14,
      },
      {
        id: "mat-7-6",
        title: "Ângulos",
        description: "Tipos de ângulos e medição de ângulos",
        videoId: "qqC72EpqTuY",
        duration: 12,
      },
      {
        id: "mat-7-7",
        title: "Triângulos",
        description: "Propriedades e classificação de triângulos",
        videoId: "feoKu12fsEQ",
        duration: 13,
      },
    ],
    quizzes: [
      {
        id: "quiz-mat-7-1",
        lessonId: "mat-7-1",
        question: "Qual é o resultado de -5 + 3?",
        options: ["-8", "-2", "2", "8"],
        correctAnswer: 1,
        explanation: "-5 + 3 = -2. Somando um número negativo com positivo.",
      },
      {
        id: "quiz-mat-7-2",
        lessonId: "mat-7-1",
        question: "Qual é o resultado de -4 × -3?",
        options: ["-12", "-7", "7", "12"],
        correctAnswer: 3,
        explanation: "Negativo vezes negativo é positivo: -4 × -3 = 12.",
      },
      {
        id: "quiz-mat-7-3",
        lessonId: "mat-7-2",
        question: "Se x + 5 = 12, qual é o valor de x?",
        options: ["5", "7", "12", "17"],
        correctAnswer: 1,
        explanation: "x + 5 = 12, então x = 12 - 5 = 7.",
      },
      {
        id: "quiz-mat-7-4",
        lessonId: "mat-7-3",
        question: "Se a razão entre dois números é 2:3 e o primeiro é 6, qual é o segundo?",
        options: ["4", "8", "9", "12"],
        correctAnswer: 2,
        explanation: "Se 6:x = 2:3, então x = 6 × 3/2 = 9.",
      },
    ],
  },

  // 7º ano - Português
  {
    subject: "portugues",
    grade: "7º ano",
    lessons: [
      {
        id: "port-7-1",
        title: "Verbos - Tempos Verbais",
        description: "Presente, passado e futuro - conjugação de verbos com Eduardo Gafa",
        videoId: "Yhhvu3DqnPY",
        duration: 16,
      },
      {
        id: "port-7-2",
        title: "Análise Sintática",
        description: "Sujeito, predicado e complementos",
        videoId: "_1n0nhz4miQ",
        duration: 12,
      },
      {
        id: "port-7-3",
        title: "Literatura - Gêneros",
        description: "Narrativo, lírico e dramático",
        videoId: "alAXSk8ly-o",
        duration: 13,
      },
      {
        id: "port-7-4",
        title: "Advérbios",
        description: "Advérbios e sua classificação",
        videoId: "2d6PW3xp2pA",
        duration: 11,
      },
    ],
    quizzes: [
      {
        id: "quiz-port-7-1",
        lessonId: "port-7-1",
        question: "Em qual tempo verbal está o verbo 'comi'?",
        options: ["Presente", "Passado", "Futuro", "Condicional"],
        correctAnswer: 1,
        explanation: "'Comi' é o pretérito perfeito, um tempo verbal do passado.",
      },
      {
        id: "quiz-port-7-2",
        lessonId: "port-7-1",
        question: "Qual é a primeira pessoa do singular do verbo 'ser' no presente?",
        options: ["Sou", "Somos", "Sois", "São"],
        correctAnswer: 0,
        explanation: "'Sou' é a primeira pessoa do singular do verbo 'ser' no presente.",
      },
      {
        id: "quiz-port-7-3",
        lessonId: "port-7-2",
        question: "Na frase 'O gato comeu o rato', qual é o sujeito?",
        options: ["O gato", "Comeu", "O rato", "Nenhum"],
        correctAnswer: 0,
        explanation: "'O gato' é o sujeito, a palavra ou termo que realiza a ação.",
      },
      {
        id: "quiz-port-7-4",
        lessonId: "port-7-3",
        question: "Qual gênero literário expressa sentimentos e emoções?",
        options: ["Narrativo", "Lírico", "Dramático", "Descritivo"],
        correctAnswer: 1,
        explanation: "O gênero lírico expressa sentimentos e emoções do poeta.",
      },
    ],
  },

  // 8º ano - Matemática
  {
    subject: "matematica",
    grade: "8º ano",
    lessons: [
      {
        id: "mat-8-1",
        title: "Expressões Algébricas",
        description: "Simplificação e fatoração - Canal Futura",
        videoId: "J-WuYxWcuZY",
        duration: 15,
      },
      {
        id: "mat-8-2",
        title: "Produtos Notáveis",
        description: "Quadrado da soma e diferença - Canal Futura",
        videoId: "0-3Du0JYXiQ",
        duration: 14,
      },
      {
        id: "mat-8-3",
        title: "Teorema de Pitágoras",
        description: "Relação entre lados de triângulos retângulos",
        videoId: "wMNiGWcaYo4",
        duration: 16,
      },
      {
        id: "mat-8-4",
        title: "Sistemas de Equações",
        description: "Resolvendo sistemas de duas equações",
        videoId: "qL4Ry5MlEzU",
        duration: 17,
      },
      {
        id: "mat-8-5",
        title: "Polígonos",
        description: "Classificação e propriedades dos polígonos",
        videoId: "4t-GMzHeXmM",
        duration: 13,
      },
    ],
    quizzes: [
      {
        id: "quiz-mat-8-1",
        lessonId: "mat-8-1",
        question: "Qual é a forma fatorada de x² + 2x + 1?",
        options: ["(x + 1)²", "(x - 1)²", "(x + 2)²", "(x² + 1)"],
        correctAnswer: 0,
        explanation: "x² + 2x + 1 = (x + 1)². Este é um trinômio quadrado perfeito.",
      },
      {
        id: "quiz-mat-8-2",
        lessonId: "mat-8-2",
        question: "Qual é o valor de (a + b)²?",
        options: [
          "a² + b²",
          "a² + 2ab + b²",
          "a² - 2ab + b²",
          "a + b",
        ],
        correctAnswer: 1,
        explanation: "(a + b)² = a² + 2ab + b². Este é um produto notável importante.",
      },
      {
        id: "quiz-mat-8-3",
        lessonId: "mat-8-3",
        question: "Em um triângulo retângulo com catetos 3 e 4, qual é a hipotenusa?",
        options: ["5", "6", "7", "8"],
        correctAnswer: 0,
        explanation: "Pelo Teorema de Pitágoras: 3² + 4² = 9 + 16 = 25, então c = √25 = 5.",
      },
    ],
  },

  // 9º ano - Matemática
  {
    subject: "matematica",
    grade: "9º ano",
    lessons: [
      {
        id: "mat-9-1",
        title: "Equações do 2º Grau",
        description: "Fórmula de Bhaskara e soluções - Portal OBMEP",
        videoId: "C0lKIgwc5nw",
        duration: 20,
      },
      {
        id: "mat-9-2",
        title: "Funções Quadráticas",
        description: "Parábolas e representação gráfica - Portal OBMEP",
        videoId: "yq9FqkWDXs0",
        duration: 18,
      },
      {
        id: "mat-9-3",
        title: "Trigonometria Básica",
        description: "Seno, cosseno e tangente - Portal OBMEP",
        videoId: "EbLj2H41a-A",
        duration: 22,
      },
      {
        id: "mat-9-4",
        title: "Semelhança de Triângulos",
        description: "Teorema de Tales e aplicações",
        videoId: "6IutDNpJ0HM",
        duration: 19,
      },
      {
        id: "mat-9-5",
        title: "Teorema de Pitágoras",
        description: "Aplicações e demonstrações",
        videoId: "IBksri8UNko",
        duration: 17,
      },
    ],
    quizzes: [
      {
        id: "quiz-mat-9-1",
        lessonId: "mat-9-1",
        question: "Qual é o discriminante da equação x² + 2x + 1 = 0?",
        options: ["-3", "0", "1", "4"],
        correctAnswer: 1,
        explanation: "Δ = b² - 4ac = 4 - 4(1)(1) = 0. Quando Δ = 0, há uma única solução real.",
      },
      {
        id: "quiz-mat-9-2",
        lessonId: "mat-9-1",
        question: "Quantas soluções reais tem a equação x² - 2x + 5 = 0?",
        options: ["0", "1", "2", "Infinitas"],
        correctAnswer: 0,
        explanation: "Δ = 4 - 20 = -16 < 0. Quando o discriminante é negativo, não há soluções reais.",
      },
      {
        id: "quiz-mat-9-3",
        lessonId: "mat-9-2",
        question: "Uma parábola com a > 0 tem concavidade para qual direção?",
        options: ["Para baixo", "Para cima", "Para direita", "Para esquerda"],
        correctAnswer: 1,
        explanation: "Quando a > 0, a parábola tem concavidade voltada para cima.",
      },
      {
        id: "quiz-mat-9-4",
        lessonId: "mat-9-3",
        question: "Em um triângulo retângulo, o seno é igual a:",
        options: [
          "Adjacente/Hipotenusa",
          "Oposto/Hipotenusa",
          "Oposto/Adjacente",
          "Hipotenusa/Oposto",
        ],
        correctAnswer: 1,
        explanation: "Seno = Cateto Oposto / Hipotenusa.",
      },
    ],
  },


  // 8º ano - Português
  {
    subject: "portugues",
    grade: "8º ano",
    lessons: [
      {
        id: "port-8-1",
        title: "Coesão Textual",
        description: "Conectivos e elementos de coesão em textos",
        videoId: "_RqhzhuRajU",
        duration: 13,
      },
      {
        id: "port-8-2",
        title: "Figuras de Linguagem",
        description: "Metáfora, metonímia, hipérbole e outras",
        videoId: "n0e75nRstcU",
        duration: 14,
      },
      {
        id: "port-8-3",
        title: "Dissertação",
        description: "Como escrever uma dissertação argumentativa",
        videoId: "alAXSk8ly-o",
        duration: 15,
      },
      {
        id: "port-8-4",
        title: "Crase",
        description: "Uso e aplicação da crase",
        videoId: "1aoM2HPwFgQ",
        duration: 12,
      },
    ],
    quizzes: [
      {
        id: "quiz-port-8-1",
        lessonId: "port-8-1",
        question: "Qual é a principal função dos conectivos em um texto?",
        options: ["Decorar o texto", "Ligar ideias e estabelecer relações", "Confundir o leitor", "Aumentar o tamanho"],
        correctAnswer: 1,
        explanation: "Os conectivos ligam ideias e estabelecem relações lógicas entre as partes do texto.",
      },
      {
        id: "quiz-port-8-2",
        lessonId: "port-8-2",
        question: "Qual é a figura de linguagem em 'Ele tinha um coração de ouro'?",
        options: ["Metonímia", "Metáfora", "Hipérbole", "Anáfora"],
        correctAnswer: 1,
        explanation: "É uma metáfora, pois compara o coração a ouro para indicar bondade.",
      },
      {
        id: "quiz-port-8-3",
        lessonId: "port-8-3",
        question: "Qual é o objetivo principal de uma dissertação?",
        options: ["Contar uma história", "Defender um ponto de vista com argumentos", "Descrever um local", "Instruir o leitor"],
        correctAnswer: 1,
        explanation: "A dissertação tem como objetivo defender um ponto de vista com argumentos sólidos.",
      },
      {
        id: "quiz-port-8-4",
        lessonId: "port-8-1",
        question: "O conectivo 'entretanto' indica qual tipo de relação?",
        options: ["Adição", "Consequência", "Contraste", "Explicação"],
        correctAnswer: 2,
        explanation: "'Entretanto' indica uma relação de contraste ou oposição entre ideias.",
      },
    ],
  },

  // 9º ano - Português
  {
    subject: "portugues",
    grade: "9º ano",
    lessons: [
      {
        id: "port-9-1",
        title: "Modernismo Brasileiro",
        description: "Primeira, segunda e terceira geração do Modernismo",
        videoId: "_1n0nhz4miQ",
        duration: 16,
      },
      {
        id: "port-9-2",
        title: "Análise de Poesias",
        description: "Recursos estilísticos em poesias modernas",
        videoId: "alAXSk8ly-o",
        duration: 13,
      },
      {
        id: "port-9-3",
        title: "Redação ENEM",
        description: "Técnicas e estrutura para redação de dissertação",
        videoId: "29l3rTMunHQ",
        duration: 17,
      },
    ],
    quizzes: [
      {
        id: "quiz-port-9-1",
        lessonId: "port-9-1",
        question: "Em que ano começou o Modernismo Brasileiro?",
        options: ["1912", "1922", "1930", "1945"],
        correctAnswer: 1,
        explanation: "O Modernismo Brasileiro começou em 1922 com a Semana de Arte Moderna de São Paulo.",
      },
      {
        id: "quiz-port-9-2",
        lessonId: "port-9-1",
        question: "Qual poeta é associado à primeira geração do Modernismo?",
        options: ["Carlos Drummond de Andrade", "Mário de Andrade", "Cecília Meireles", "João Cabral de Melo Neto"],
        correctAnswer: 1,
        explanation: "Mário de Andrade foi um dos principais poetas da primeira geração do Modernismo.",
      },
      {
        id: "quiz-port-9-3",
        lessonId: "port-9-2",
        question: "Qual é o recurso estilístico em 'O silêncio grita'?",
        options: ["Metonímia", "Oxímoro", "Hipérbole", "Antítese"],
        correctAnswer: 1,
        explanation: "É um oxímoro, pois combina palavras de significados contraditórios (silêncio e grita).",
      },
      {
        id: "quiz-port-9-4",
        lessonId: "port-9-3",
        question: "Quantos parágrafos tem uma dissertação ENEM padrão?",
        options: ["Dois", "Três", "Quatro", "Cinco"],
        correctAnswer: 1,
        explanation: "Uma dissertação ENEM padrão tem três parágrafos: introdução, desenvolvimento e conclusão.",
      },
    ],
  },

  // 7º ano - História
  {
    subject: "historia",
    grade: "7º ano",
    lessons: [
      {
        id: "hist-7-1",
        title: "Feudalismo",
        description: "Sistema feudal na Idade Média europeia",
        videoId: "0x74kH0MpqQ",
        duration: 14,
      },
      {
        id: "hist-7-2",
        title: "Renascimento",
        description: "Movimento cultural e artístico europeu",
        videoId: "_T1C5prUbic",
        duration: 13,
      },
      {
        id: "hist-7-3",
        title: "Grande Navegações",
        description: "Época de Ouro das navegações portuguesas e espanholas",
        videoId: "AN_byow1mWk",
        duration: 12,
      },
    ],
    quizzes: [
      {
        id: "quiz-hist-7-1",
        lessonId: "hist-7-1",
        question: "Qual era a base econômica do Feudalismo?",
        options: ["Comércio", "Agricultura", "Manufatura", "Mineração"],
        correctAnswer: 1,
        explanation: "A base econômica do Feudalismo era a agricultura, com servos trabalhando as terras dos senhores.",
      },
      {
        id: "quiz-hist-7-2",
        lessonId: "hist-7-2",
        question: "Em qual período ocorreu o Renascimento?",
        options: ["Século XIV-XVI", "Século XVII-XVIII", "Século XII-XIII", "Século XIX-XX"],
        correctAnswer: 0,
        explanation: "O Renascimento ocorreu entre os séculos XIV e XVI, principalmente na Itália.",
      },
      {
        id: "quiz-hist-7-3",
        lessonId: "hist-7-3",
        question: "Qual navegador português famoso explorou o caminho para a Índia?",
        options: ["Bartolomeu Dias", "Vasco da Gama", "Pedro Álvares Cabral", "Fernão de Magalhães"],
        correctAnswer: 1,
        explanation: "Vasco da Gama foi o navegador que chegou à Índia em 1498.",
      },
      {
        id: "quiz-hist-7-4",
        lessonId: "hist-7-1",
        question: "Qual era o estatuto social de um servo no Feudalismo?",
        options: ["Livre", "Preso à terra", "Escravo do rei", "Comerciante"],
        correctAnswer: 1,
        explanation: "O servo era preso à terra, devendo trabalhar para o senhor feudal.",
      },
    ],
  },

  // 8º ano - História
  {
    subject: "historia",
    grade: "8º ano",
    lessons: [
      {
        id: "hist-8-1",
        title: "Iluminismo",
        description: "Movimento filosófico do século XVIII",
        videoId: "_T1C5prUbic",
        duration: 13,
      },
      {
        id: "hist-8-2",
        title: "Revolução Francesa",
        description: "Causas, fases e consequências da Revolução Francesa",
        videoId: "0x74kH0MpqQ",
        duration: 15,
      },
      {
        id: "hist-8-3",
        title: "Brasil Colonial",
        description: "Economia e sociedade no período colonial brasileiro",
        videoId: "BzADvI7MAKg",
        duration: 14,
      },
    ],
    quizzes: [
      {
        id: "quiz-hist-8-1",
        lessonId: "hist-8-1",
        question: "Qual é o lema do Iluminismo?",
        options: ["Fé e tradição", "Razão e Ciência", "Emoção e arte", "Poder absoluto"],
        correctAnswer: 1,
        explanation: "O lema do Iluminismo é a razão e a ciência como base para o conhecimento.",
      },
      {
        id: "quiz-hist-8-2",
        lessonId: "hist-8-2",
        question: "Em que ano começou a Revolução Francesa?",
        options: ["1776", "1789", "1799", "1815"],
        correctAnswer: 1,
        explanation: "A Revolução Francesa começou em 1789 com a queda da Bastilha.",
      },
      {
        id: "quiz-hist-8-3",
        lessonId: "hist-8-3",
        question: "Qual era o principal produto de exportação do Brasil colonial?",
        options: ["Algodão", "Açúcar", "Café", "Minério"],
        correctAnswer: 1,
        explanation: "O açúcar era o principal produto de exportação durante o período colonial.",
      },
      {
        id: "quiz-hist-8-4",
        lessonId: "hist-8-2",
        question: "Qual foi um dos direitos declarados pela Revolução Francesa?",
        options: ["Servidão", "Escravidão", "Igualdade de direitos", "Monarquia absoluta"],
        correctAnswer: 2,
        explanation: "A Revolução Francesa defendia a igualdade de direitos entre os cidadãos.",
      },
    ],
  },

  // 9º ano - História
  {
    subject: "historia",
    grade: "9º ano",
    lessons: [
      {
        id: "hist-9-1",
        title: "Revoluções Industriais",
        description: "1ª, 2ª e 3ª Revolução Industrial - YouTube Edu",
        videoId: "zfUiiph2CKs",
        duration: 18,
      },
      {
        id: "hist-9-2",
        title: "Imperialismo Europeu",
        description: "Expansão imperial europeia na Ásia e África",
        videoId: "jESCa-w1peE",
        duration: 16,
      },
      {
        id: "hist-9-3",
        title: "Primeira Guerra Mundial",
        description: "Causas, desenvolvimento e consequências",
        videoId: "3BjmUMNRqro",
        duration: 20,
      },
      {
        id: "hist-9-4",
        title: "Segunda Guerra Mundial",
        description: "O conflito mundial e suas consequências",
        videoId: "bbGFH1nGFq0",
        duration: 22,
      },
      {
        id: "hist-9-5",
        title: "Guerra Fria",
        description: "Disputa entre EUA e URSS",
        videoId: "vkhw9kFmOdk",
        duration: 19,
      },
    ],
    quizzes: [
      {
        id: "quiz-hist-9-1",
        lessonId: "hist-9-1",
        question: "Quando começou a Primeira Revolução Industrial?",
        options: ["Século XVII", "Século XVIII", "Século XIX", "Século XX"],
        correctAnswer: 1,
        explanation: "A Primeira Revolução Industrial começou no século XVIII, em torno de 1760.",
      },
      {
        id: "quiz-hist-9-2",
        lessonId: "hist-9-2",
        question: "Qual foi a principal motivação para o Imperialismo Europeu?",
        options: ["Expansão religiosa", "Busca de matérias-primas e mercados", "Ganho de conhecimento", "Ajuda a povos colonizados"],
        correctAnswer: 1,
        explanation: "O Imperialismo foi motivado pela busca de matérias-primas, mercados e domínio político.",
      },
      {
        id: "quiz-hist-9-3",
        lessonId: "hist-9-3",
        question: "Em que ano terminou a Primeira Guerra Mundial?",
        options: ["1915", "1918", "1920", "1925"],
        correctAnswer: 1,
        explanation: "A Primeira Guerra Mundial terminou em 1918 com a vitória dos Aliados.",
      },
      {
        id: "quiz-hist-9-4",
        lessonId: "hist-9-1",
        question: "Qual foi o combustível principal da Segunda Revolução Industrial?",
        options: ["Carvão", "Eletricidade e petróleo", "Lenha", "Energia solar"],
        correctAnswer: 1,
        explanation: "A Segunda Revolução Industrial (século XIX) foi alimentada por eletricidade e petróleo.",
      },
    ],
  },

  // 7º ano - Geografia
  {
    subject: "geografia",
    grade: "7º ano",
    lessons: [
      {
        id: "geog-7-1",
        title: "Regiões do Brasil",
        description: "Características geográficas das regiões brasileiras",
        videoId: "-EnodYhcQw4",
        duration: 14,
      },
      {
        id: "geog-7-2",
        title: "Principais Rios",
        description: "Rios brasileiros e sua importância econômica",
        videoId: "_1UaytDLMGk",
        duration: 12,
      },
      {
        id: "geog-7-3",
        title: "Economia Brasileira",
        description: "Setores econômicos e principais atividades",
        videoId: "_XNTrI8rAZI",
        duration: 13,
      },
    ],
    quizzes: [
      {
        id: "quiz-geog-7-1",
        lessonId: "geog-7-1",
        question: "Quantas regiões geográficas tem o Brasil?",
        options: ["3", "4", "5", "6"],
        correctAnswer: 2,
        explanation: "O Brasil tem 5 regiões: Norte, Nordeste, Centro-Oeste, Sudeste e Sul.",
      },
      {
        id: "quiz-geog-7-2",
        lessonId: "geog-7-2",
        question: "Qual é o maior rio do Brasil?",
        options: ["Rio de Janeiro", "Rio Amazonas", "Rio São Francisco", "Rio Paraná"],
        correctAnswer: 1,
        explanation: "O Rio Amazonas é o maior rio do Brasil e do mundo em volume de água.",
      },
      {
        id: "quiz-geog-7-3",
        lessonId: "geog-7-3",
        question: "Qual é o setor econômico mais importante do Brasil?",
        options: ["Agricultura", "Indústria", "Serviços", "Mineração"],
        correctAnswer: 2,
        explanation: "O setor de serviços é o mais importante da economia brasileira atualmente.",
      },
      {
        id: "quiz-geog-7-4",
        lessonId: "geog-7-1",
        question: "Qual região do Brasil é a mais populosa?",
        options: ["Norte", "Nordeste", "Sudeste", "Sul"],
        correctAnswer: 2,
        explanation: "A região Sudeste é a mais populosa e desenvolvida do Brasil.",
      },
    ],
  },

  // 8º ano - Geografia
  {
    subject: "geografia",
    grade: "8º ano",
    lessons: [
      {
        id: "geog-8-1",
        title: "Globalização",
        description: "Processo de integração global e seus impactos",
        videoId: "BccU6aDEuC0",
        duration: 14,
      },
      {
        id: "geog-8-2",
        title: "Geopolítica",
        description: "Conflitos territoriais e poder político no mundo",
        videoId: "_XNTrI8rAZI",
        duration: 13,
      },
      {
        id: "geog-8-3",
        title: "Recursos Naturais",
        description: "Recursos renováveis e não renováveis",
        videoId: "_1UaytDLMGk",
        duration: 12,
      },
    ],
    quizzes: [
      {
        id: "quiz-geog-8-1",
        lessonId: "geog-8-1",
        question: "Qual é uma característica da globalização?",
        options: ["Isolamento dos países", "Integração econômica e cultural", "Fortalecimento de fronteiras", "Redução do comércio"],
        correctAnswer: 1,
        explanation: "A globalização é caracterizada pela integração econômica, cultural e tecnológica entre países.",
      },
      {
        id: "quiz-geog-8-2",
        lessonId: "geog-8-2",
        question: "O que estuda a Geopolítica?",
        options: ["Apenas o relevo", "Conflitos e poder político territorial", "Apenas climas", "Minerais e rochas"],
        correctAnswer: 1,
        explanation: "A Geopolítica estuda os conflitos territoriais e o poder político no espaço geográfico.",
      },
      {
        id: "quiz-geog-8-3",
        lessonId: "geog-8-3",
        question: "Qual é um exemplo de recurso natural renovável?",
        options: ["Petróleo", "Carvão", "Energia solar", "Minério"],
        correctAnswer: 2,
        explanation: "A energia solar é um recurso renovável, diferentemente do petróleo que é não-renovável.",
      },
      {
        id: "quiz-geog-8-4",
        lessonId: "geog-8-1",
        question: "Qual é um impacto negativo da globalização?",
        options: ["Maior comércio", "Desigualdade social", "Mais tecnologia", "Melhor comunicação"],
        correctAnswer: 1,
        explanation: "A globalização pode aumentar a desigualdade entre países ricos e pobres.",
      },
    ],
  },

  // 9º ano - Geografia
  {
    subject: "geografia",
    grade: "9º ano",
    lessons: [
      {
        id: "geog-9-1",
        title: "Organização Geopolítica",
        description: "Estados, nações e territórios no mundo contemporâneo",
        videoId: "_T1C5prUbic",
        duration: 15,
      },
      {
        id: "geog-9-2",
        title: "Desenvolvimento Sustentável",
        description: "Desafios ambientais e sustentabilidade",
        videoId: "0x74kH0MpqQ",
        duration: 14,
      },
      {
        id: "geog-9-3",
        title: "Urbanização",
        description: "Crescimento das cidades e problemas urbanos",
        videoId: "AN_byow1mWk",
        duration: 13,
      },
    ],
    quizzes: [
      {
        id: "quiz-geog-9-1",
        lessonId: "geog-9-1",
        question: "Qual é a diferença entre estado e nação?",
        options: ["Não há diferença", "Estado é político, nação é cultural", "São termos sinônimos", "Nação tem mais poder"],
        correctAnswer: 1,
        explanation: "Estado refere-se à organização política, enquanto nação refere-se a um grupo com identidade cultural comum.",
      },
      {
        id: "quiz-geog-9-2",
        lessonId: "geog-9-2",
        question: "Qual é o principal objetivo do desenvolvimento sustentável?",
        options: ["Crescimento econômico rápido", "Equilíbrio entre economia e ambiente", "Maximizar a exploração", "Parar a industrialização"],
        correctAnswer: 1,
        explanation: "O desenvolvimento sustentável busca equilibrar crescimento econômico com preservação ambiental.",
      },
      {
        id: "quiz-geog-9-3",
        lessonId: "geog-9-3",
        question: "Qual é um dos principais problemas das metrópoles?",
        options: ["Falta de pessoas", "Tráfego e poluição", "Excesso de vegetação", "Pouca tecnologia"],
        correctAnswer: 1,
        explanation: "Metrópoles enfrentam problemas como tráfego congestionado e poluição do ar e água.",
      },
      {
        id: "quiz-geog-9-4",
        lessonId: "geog-9-1",
        question: "Qual é um desafio da globalização para o planeta?",
        options: ["Nenhum", "Maior consumo e poluição", "Redução de conflitos", "Igualdade perfeita"],
        correctAnswer: 1,
        explanation: "A globalização aumenta o consumo e consequentemente a poluição ambiental.",
      },
    ],
  },

  // 7º ano - Inglês
  {
    subject: "ingles",
    grade: "7º ano",
    lessons: [
      {
        id: "eng-7-1",
        title: "Verb Tenses - Present Perfect",
        description: "Present Perfect tense - have/has + past participle",
        videoId: "AE3cwqdqXBc",
        duration: 12,
      },
      {
        id: "eng-7-2",
        title: "Modal Verbs",
        description: "Can, could, may, might, must, should",
        videoId: "_fmAYE-T0hg",
        duration: 11,
      },
      {
        id: "eng-7-3",
        title: "Phrasal Verbs",
        description: "Common phrasal verbs and their meanings",
        videoId: "HzCVOyP6wg0",
        duration: 14,
      },
    ],
    quizzes: [
      {
        id: "quiz-eng-7-1",
        lessonId: "eng-7-1",
        question: "How do we form the Present Perfect tense?",
        options: ["Verb + ed", "Have/Has + past participle", "Will + verb", "Is/Are + ing"],
        correctAnswer: 1,
        explanation: "The Present Perfect is formed with have/has + past participle.",
      },
      {
        id: "quiz-eng-7-2",
        lessonId: "eng-7-2",
        question: "Which modal verb expresses obligation?",
        options: ["Can", "May", "Must", "Could"],
        correctAnswer: 2,
        explanation: "'Must' is used to express obligation or strong necessity.",
      },
      {
        id: "quiz-eng-7-3",
        lessonId: "eng-7-3",
        question: "What does 'look after' mean?",
        options: ["Procurar", "Cuidar de", "Olhar para", "Buscar"],
        correctAnswer: 1,
        explanation: "'Look after' is a phrasal verb meaning 'cuidar de' or 'take care of'.",
      },
      {
        id: "quiz-eng-7-4",
        lessonId: "eng-7-1",
        question: "Complete: 'I have ___ to London three times.'",
        options: ["go", "went", "gone", "going"],
        correctAnswer: 2,
        explanation: "The correct form is 'gone' - the past participle of go.",
      },
    ],
  },

  // 8º ano - Inglês
  {
    subject: "ingles",
    grade: "8º ano",
    lessons: [
      {
        id: "eng-8-1",
        title: "Conditional Sentences",
        description: "First, Second, and Third conditionals",
        videoId: "AE3cwqdqXBc",
        duration: 14,
      },
      {
        id: "eng-8-2",
        title: "Reported Speech",
        description: "Changing direct speech to reported speech",
        videoId: "_fmAYE-T0hg",
        duration: 13,
      },
      {
        id: "eng-8-3",
        title: "Passive Voice",
        description: "Formation and use of passive voice",
        videoId: "8bKJj2BFe94",
        duration: 15,
      },
      {
        id: "eng-8-4",
        title: "Modal Verbs - Advanced",
        description: "Must, Should, Could, May, Might - usos avançados",
        videoId: "xPlLan5N4k0",
        duration: 16,
      },
      {
        id: "eng-8-5",
        title: "Future Forms",
        description: "Will, Going to, Present Continuous for Future",
        videoId: "HihcrKORJEI",
        duration: 14,
      },
      {
        id: "eng-8-6",
        title: "Relative Pronouns",
        description: "Who, Which, That, Whose, Where",
        videoId: "h7K-vCAPLEU",
        duration: 15,
      },
      {
        id: "eng-8-7",
        title: "Question Tags",
        description: "Formation and usage of question tags",
        videoId: "tgz-JzWbBLs",
        duration: 12,
      },
      {
        id: "eng-8-8",
        title: "Gerunds and Infinitives",
        description: "When to use -ing or to + verb",
        videoId: "C5xXQJ6ko4o",
        duration: 17,
      },
      {
        id: "eng-8-9",
        title: "Comparatives and Superlatives",
        description: "Advanced comparison structures",
        videoId: "qKCuOk2i-dM",
        duration: 13,
      },
      {
        id: "eng-8-10",
        title: "Linking Words",
        description: "Connectors and discourse markers",
        videoId: "xS0fRDXBq40",
        duration: 14,
      },
      {
        id: "eng-8-11",
        title: "Present Perfect Continuous",
        description: "Usage and formation",
        videoId: "7I9keAIL5aQ",
        duration: 15,
      },
      {
        id: "eng-8-12",
        title: "Past Perfect",
        description: "Talking about past before past",
        videoId: "VeVSGKfVvs4",
        duration: 14,
      },
      {
        id: "eng-8-13",
        title: "Used to / Would",
        description: "Talking about past habits",
        videoId: "QeTQGJr7cPU",
        duration: 13,
      },
      {
        id: "eng-8-14",
        title: "Prefixes and Suffixes",
        description: "Word formation in English",
        videoId: "kN6DVX_5e_A",
        duration: 16,
      },
    ],
    quizzes: [
      {
        id: "quiz-eng-8-1",
        lessonId: "eng-8-1",
        question: "What is the structure of the First Conditional?",
        options: ["If + would, would verb", "If + present, will + verb", "If + past, would verb", "If + will, would verb"],
        correctAnswer: 1,
        explanation: "First Conditional: If + present simple, will + base verb",
      },
      {
        id: "quiz-eng-8-2",
        lessonId: "eng-8-2",
        question: "Change to reported speech: 'I am happy' he said.",
        options: ["He said I am happy", "He said he was happy", "He said he is happy", "He said I was happy"],
        correctAnswer: 1,
        explanation: "In reported speech, 'am' changes to 'was' and the subject changes to 'he'.",
      },
      {
        id: "quiz-eng-8-3",
        lessonId: "eng-8-3",
        question: "Change to passive: 'They built the house'",
        options: ["The house was build", "The house was built", "The house were built", "The house is built"],
        correctAnswer: 1,
        explanation: "Passive voice: The house was built (be + past participle).",
      },
      {
        id: "quiz-eng-8-4",
        lessonId: "eng-8-1",
        question: "What does the Second Conditional express?",
        options: ["Real future situations", "Impossible/unlikely situations", "Past events", "General truths"],
        correctAnswer: 1,
        explanation: "The Second Conditional expresses hypothetical or unlikely situations in the present/future.",
      },
    ],
  },

  // 9º ano - Inglês
  {
    subject: "ingles",
    grade: "9º ano",
    lessons: [
      {
        id: "eng-9-1",
        title: "Advanced Grammar",
        description: "Relative clauses, mixed conditionals, and advanced structures",
        videoId: "AE3cwqdqXBc",
        duration: 15,
      },
      {
        id: "eng-9-2",
        title: "Vocabulary Building",
        description: "Advanced vocabulary and word families",
        videoId: "_fmAYE-T0hg",
        duration: 13,
      },
      {
        id: "eng-9-3",
        title: "Listening Comprehension",
        description: "Strategies for improving listening skills",
        videoId: "m6eF1af6LqA",
        duration: 13,
      },
      {
        id: "eng-9-4",
        title: "Phrasal Verbs - Set 1",
        description: "Common phrasal verbs: get, take, put",
        videoId: "5hEOguWWgTk",
        duration: 16,
      },
      {
        id: "eng-9-5",
        title: "Phrasal Verbs - Set 2",
        description: "More phrasal verbs: look, turn, give",
        videoId: "VKAGKs3bLBo",
        duration: 15,
      },
      {
        id: "eng-9-6",
        title: "Idioms and Expressions",
        description: "Common English idioms explained",
        videoId: "oR3sHVZXU_s",
        duration: 14,
      },
      {
        id: "eng-9-7",
        title: "Advanced Tenses",
        description: "Future Perfect, Past Perfect Continuous",
        videoId: "d9bK8TlKXME",
        duration: 17,
      },
      {
        id: "eng-9-8",
        title: "Mixed Conditionals",
        description: "Combining conditional forms",
        videoId: "t-tRkIhSg10",
        duration: 15,
      },
      {
        id: "eng-9-9",
        title: "Collocations",
        description: "Words that go together naturally",
        videoId: "kQz-gBBxJ2g",
        duration: 14,
      },
      {
        id: "eng-9-10",
        title: "Formal vs Informal English",
        description: "Register and appropriate language use",
        videoId: "3APSc5h-xE0",
        duration: 13,
      },
      {
        id: "eng-9-11",
        title: "Writing Skills - Essays",
        description: "How to structure an essay",
        videoId: "o2xjFFXlKaM",
        duration: 18,
      },
      {
        id: "eng-9-12",
        title: "Reading Strategies",
        description: "Skimming, scanning, detailed reading",
        videoId: "e3FUQaADNjg",
        duration: 16,
      },
      {
        id: "eng-9-13",
        title: "Pronunciation Practice",
        description: "Difficult sounds for Portuguese speakers",
        videoId: "w4pO97FIY04",
        duration: 15,
      },
      {
        id: "eng-9-14",
        title: "False Friends",
        description: "Words that look similar but mean different things",
        videoId: "5x8d6_R-d_A",
        duration: 12,
      },
      {
        id: "eng-9-15",
        title: "British vs American English",
        description: "Differences in vocabulary and spelling",
        videoId: "LMkKCTaUlK0",
        duration: 14,
      },
      {
        id: "eng-9-16",
        title: "Business English Basics",
        description: "Professional vocabulary and phrases",
        videoId: "kkU0_Ga2PnU",
        duration: 15,
      },
      {
        id: "eng-9-17",
        title: "Conversation Skills",
        description: "How to keep a conversation going",
        videoId: "JqHiQ79ZsGU",
        duration: 13,
      },
    ],
    quizzes: [
      {
        id: "quiz-eng-9-1",
        lessonId: "eng-9-1",
        question: "What is a relative clause?",
        options: ["A clause about family", "A clause that adds information about a noun", "A dependent clause", "A main clause"],
        correctAnswer: 1,
        explanation: "A relative clause adds information about a noun using relative pronouns like who, which, that.",
      },
      {
        id: "quiz-eng-9-2",
        lessonId: "eng-9-2",
        question: "What does 'eloquent' mean?",
        options: ["Quiet", "Fluent and persuasive in speech", "Elegant", "Excellent"],
        correctAnswer: 1,
        explanation: "'Eloquent' means fluent, persuasive, and expressive in speech or writing.",
      },
      {
        id: "quiz-eng-9-3",
        lessonId: "eng-9-3",
        question: "Which is a good strategy for listening comprehension?",
        options: ["Translate everything mentally", "Listen to key words and context clues", "Look at the speaker", "Write down every word"],
        correctAnswer: 1,
        explanation: "Listening for key words and using context clues helps with comprehension.",
      },
      {
        id: "quiz-eng-9-4",
        lessonId: "eng-9-1",
        question: "Complete: 'If I had studied, I ___ passed the exam.'",
        options: ["would pass", "would have passed", "will pass", "have passed"],
        correctAnswer: 1,
        explanation: "Third Conditional: If + past perfect, would + have + past participle.",
      },
    ],
  },

  // CIÊNCIAS - 6º ano
  {
    subject: "ciencias",
    grade: "6º ano",
    lessons: [
      {
        id: "cie-6-1",
        title: "O Método Científico",
        description: "Como os cientistas trabalham",
        videoId: "C_0-qm48IKs",
        duration: 12,
      },
      {
        id: "cie-6-2",
        title: "Células - Unidade da Vida",
        description: "Estrutura e função celular",
        videoId: "FgTkXS-4ICY",
        duration: 15,
      },
      {
        id: "cie-6-3",
        title: "Água e Seres Vivos",
        description: "Importância da água para a vida",
        videoId: "dP94M3GJwME",
        duration: 14,
      },
      {
        id: "cie-6-4",
        title: "Nutrição e Alimentos",
        description: "Nutrientes e alimentação saudável",
        videoId: "jN0MkUuBWcc",
        duration: 16,
      },
      {
        id: "cie-6-5",
        title: "Sistema Digestório",
        description: "Como funciona a digestão",
        videoId: "d3z9OhhAR1I",
        duration: 17,
      },
      {
        id: "cie-6-6",
        title: "Sistema Respiratório",
        description: "Respiração e trocas gasosas",
        videoId: "K_qqPFnQ5LA",
        duration: 15,
      },
      {
        id: "cie-6-7",
        title: "Sistema Circulatório",
        description: "Coração, sangue e circulação",
        videoId: "bUW8d_L1O8U",
        duration: 18,
      },
      {
        id: "cie-6-8",
        title: "Solo e Rochas",
        description: "Formação e tipos de solo",
        videoId: "tnLgPpZHoJs",
        duration: 14,
      },
    ],
    quizzes: [],
  },

  // CIÊNCIAS - 7º ano
  {
    subject: "ciencias",
    grade: "7º ano",
    lessons: [
      {
        id: "cie-7-1",
        title: "Reino Animal - Invertebrados",
        description: "Poríferos, cnidários, platelmintos e mais",
        videoId: "RjzXvwUXULE",
        duration: 16,
      },
      {
        id: "cie-7-2",
        title: "Reino Animal - Vertebrados",
        description: "Peixes, anfíbios, répteis, aves e mamíferos",
        videoId: "eAFYgN0jqQU",
        duration: 18,
      },
      {
        id: "cie-7-3",
        title: "Reino Vegetal",
        description: "Plantas e suas características",
        videoId: "m7MbVTi0rYg",
        duration: 15,
      },
      {
        id: "cie-7-4",
        title: "Fotossíntese",
        description: "Como as plantas produzem alimento",
        videoId: "Sej4lTNZfk4",
        duration: 14,
      },
      {
        id: "cie-7-5",
        title: "Ecologia - Conceitos Básicos",
        description: "Ecossistemas, habitat, nicho ecológico",
        videoId: "k7FUg_aLbYY",
        duration: 17,
      },
      {
        id: "cie-7-6",
        title: "Cadeias e Teias Alimentares",
        description: "Relações alimentares nos ecossistemas",
        videoId: "YNiOzIzx1BI",
        duration: 15,
      },
      {
        id: "cie-7-7",
        title: "Relações Ecológicas",
        description: "Predação, parasitismo, mutualismo e mais",
        videoId: "zJ_F1ThuJo4",
        duration: 16,
      },
      {
        id: "cie-7-8",
        title: "Poluição Ambiental",
        description: "Tipos de poluição e impactos",
        videoId: "xQtH0VXBrz8",
        duration: 14,
      },
    ],
    quizzes: [],
  },

  // CIÊNCIAS - 8º ano
  {
    subject: "ciencias",
    grade: "8º ano",
    lessons: [
      {
        id: "cie-8-1",
        title: "Mecânica - Movimento",
        description: "Cinemática e tipos de movimento",
        videoId: "yqBjLVibv9Q",
        duration: 16,
      },
      {
        id: "cie-8-2",
        title: "Forças e Leis de Newton",
        description: "As três leis do movimento",
        videoId: "wPTnBm2RV9c",
        duration: 18,
      },
      {
        id: "cie-8-3",
        title: "Energia - Formas e Transformações",
        description: "Tipos de energia e conservação",
        videoId: "VGIoMZg2gpI",
        duration: 15,
      },
      {
        id: "cie-8-4",
        title: "Calor e Temperatura",
        description: "Diferença e escalas termométricas",
        videoId: "q-2B9Jq2o6k",
        duration: 17,
      },
      {
        id: "cie-8-5",
        title: "Ondas - Som e Luz",
        description: "Propriedades das ondas",
        videoId: "9jZNCxKF8sw",
        duration: 16,
      },
      {
        id: "cie-8-6",
        title: "Eletricidade Básica",
        description: "Cargas, corrente e circuitos",
        videoId: "RlSqRjW02L0",
        duration: 19,
      },
      {
        id: "cie-8-7",
        title: "Magnetismo",
        description: "Ímãs e campo magnético",
        videoId: "3XGl_WuIbkE",
        duration: 14,
      },
      {
        id: "cie-8-8",
        title: "Sistema Nervoso",
        description: "Neurônios e funcionamento do cérebro",
        videoId: "e7EEhPBQlV8",
        duration: 17,
      },
    ],
    quizzes: [],
  },

  // CIÊNCIAS - 9º ano
  {
    subject: "ciencias",
    grade: "9º ano",
    lessons: [
      {
        id: "cie-9-1",
        title: "Estrutura da Matéria",
        description: "Átomos, moléculas e elementos químicos",
        videoId: "TYDKfD8F7gE",
        duration: 16,
      },
      {
        id: "cie-9-2",
        title: "Tabela Periódica",
        description: "Organização dos elementos",
        videoId: "HFqkx_rkTRg",
        duration: 18,
      },
      {
        id: "cie-9-3",
        title: "Ligações Químicas",
        description: "Iônica, covalente e metálica",
        videoId: "Bg9f1Zq4VNs",
        duration: 17,
      },
      {
        id: "cie-9-4",
        title: "Reações Químicas",
        description: "Tipos e balanceamento de equações",
        videoId: "CqY72fWRaHw",
        duration: 15,
      },
      {
        id: "cie-9-5",
        title: "Genética - Conceitos Básicos",
        description: "DNA, genes e hereditariedade",
        videoId: "dsjXKB_zIPg",
        duration: 19,
      },
      {
        id: "cie-9-6",
        title: "Leis de Mendel",
        description: "Primeira e segunda lei da genética",
        videoId: "39wy9PFUx0k",
        duration: 18,
      },
      {
        id: "cie-9-7",
        title: "Evolução das Espécies",
        description: "Teoria de Darwin e seleção natural",
        videoId: "NZBgudNeIw0",
        duration: 16,
      },
      {
        id: "cie-9-8",
        title: "Sistema Solar e Universo",
        description: "Planetas, estrelas e galáxias",
        videoId: "W4mLnfTlBCY",
        duration: 17,
      },
      {
        id: "cie-9-9",
        title: "Radioatividade",
        description: "Radiação e suas aplicações",
        videoId: "8yy7j-DFJqU",
        duration: 15,
      },
      {
        id: "cie-9-10",
        title: "Biotecnologia",
        description: "Aplicações da biologia moderna",
        videoId: "N4IfYx6Zrfg",
        duration: 14,
      },
    ],
    quizzes: [],
  },
];

export function getSubjectInfo(subject: string) {
  return SUBJECT_INFO[subject as keyof typeof SUBJECT_INFO];
}

export function getLessons(subject: string, grade: string) {
  const item = data.find((d) => d.subject === subject && d.grade === grade);
  return item?.lessons || [];
}

export function getLesson(subject: string, grade: string, lessonId: string) {
  const item = data.find((d) => d.subject === subject && d.grade === grade);
  return item?.lessons.find((l) => l.id === lessonId);
}

export function getQuiz(subject: string, grade: string, lessonId: string) {
  const item = data.find((d) => d.subject === subject && d.grade === grade);
  return item?.quizzes.filter((q) => q.lessonId === lessonId) || [];
}
