#!/usr/bin/env node
console.log('');
console.log('═══════════════════════════════════════════════════');
console.log('🚀 CONFIGURAR BANCO DE DADOS DO CHAT');
console.log('═══════════════════════════════════════════════════');
console.log('');
console.log('📝 PASSO 1: Acesse o Supabase Studio');
console.log('   https://supabase.com/dashboard');
console.log('');
console.log('📝 PASSO 2: Vá em SQL Editor');
console.log('');
console.log('📝 PASSO 3: Cole e execute o SQL abaixo:');
console.log('');
console.log('───────────────────────────────────────────────────');
console.log('');
console.log('CREATE TABLE IF NOT EXISTS chat_messages (');
console.log('  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,');
console.log('  user_name TEXT NOT NULL,');
console.log('  message TEXT NOT NULL,');
console.log('  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),');
console.log('  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,');
console.log('  likes INTEGER DEFAULT 0');
console.log(');');
console.log('');
console.log('CREATE INDEX IF NOT EXISTS idx_chat_messages_created_at ');
console.log('ON chat_messages(created_at DESC);');
console.log('');
console.log('ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;');
console.log('');
console.log('CREATE POLICY "Anyone can read messages"');
console.log('ON chat_messages FOR SELECT');
console.log('USING (true);');
console.log('');
console.log('CREATE POLICY "Authenticated users can insert messages"');
console.log('ON chat_messages FOR INSERT');
console.log('WITH CHECK (auth.role() = \'authenticated\' OR auth.role() = \'anon\');');
console.log('');
console.log('CREATE POLICY "Users can delete their own messages"');
console.log('ON chat_messages FOR DELETE');
console.log('USING (auth.uid() = user_id);');
console.log('');
console.log('───────────────────────────────────────────────────');
console.log('');
console.log('📝 PASSO 4: Habilitar Realtime');
console.log('   Database → Replication → chat_messages → ✅');
console.log('');
console.log('🎉 PRONTO! O chat estará funcionando!');
console.log('');
console.log('🚀 Teste em: http://localhost:3000/chat');
console.log('');
console.log('═══════════════════════════════════════════════════');
console.log('');
