#!/usr/bin/env node
console.log('');
console.log('═══════════════════════════════════════════════════');
console.log('🚀 CONFIGURAR BANCO DE DADOS DO CHAT');
console.log('═══════════════════════════════════════════════════');
console.log('');
console.log('📝 PASSO 1: Acesse o Supabase Studio');
console.log('   https://supabase.com/dashboard');
console.log('');
console.log('📝 PASSO 2: Vá em SQL Editor');
console.log('');
console.log('📝 PASSO 3: Cole e execute o SQL abaixo:');
console.log('');
console.log('───────────────────────────────────────────────────');
console.log('');
console.log('-- Criar tabela de mensagens do chat');
console.log('CREATE TABLE IF NOT EXISTS chat_messages (');
console.log('  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,');
console.log('  user_name TEXT NOT NULL,');
console.log('  message TEXT NOT NULL,');
console.log('  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),');
console.log('  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,');
console.log('  likes INTEGER DEFAULT 0');
console.log(');');
console.log('');
console.log('-- Criar índice para performance');
console.log('CREATE INDEX IF NOT EXISTS idx_chat_messages_created_at');
console.log('ON chat_messages(created_at DESC);');
console.log('');
console.log('-- Habilitar Row Level Security');
console.log('ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;');
console.log('');
console.log('-- Remover policies antigas se existirem');
console.log('DROP POLICY IF EXISTS "Anyone can read messages" ON chat_messages;');
console.log('DROP POLICY IF EXISTS "Authenticated users can insert messages" ON chat_messages;');
console.log('DROP POLICY IF EXISTS "Users can delete their own messages" ON chat_messages;');
console.log('');
console.log('-- Criar policies de segurança');
console.log('CREATE POLICY "Anyone can read messages"');
console.log('ON chat_messages FOR SELECT');
console.log('USING (true);');
console.log('');
console.log('CREATE POLICY "Authenticated users can insert messages"');
console.log('ON chat_messages FOR INSERT');
console.log('WITH CHECK (auth.role() = \'authenticated\' OR auth.role() = \'anon\');');
console.log('');
console.log('CREATE POLICY "Users can delete their own messages"');
console.log('ON chat_messages FOR DELETE');
console.log('USING (auth.uid() = user_id);');
console.log('');
console.log('───────────────────────────────────────────────────');
console.log('');
console.log('📝 PASSO 4: Habilitar Realtime');
console.log('   1. No Supabase Dashboard');
console.log('   2. Vá em: Database → Replication');
console.log('   3. Procure "chat_messages"');
console.log('   4. Ative o toggle → ✅');
console.log('');
console.log('💡 NOTA: Se der erro de "policy already exists",');
console.log('   ignore! As policies já estão criadas. ✅');
console.log('');
console.log('🎉 PRONTO! O chat estará funcionando!');
console.log('');
console.log('🚀 Teste em: http://localhost:3000/chat');
console.log('   Abra em 2 abas e veja as mensagens em tempo real!');
console.log('');
console.log('═══════════════════════════════════════════════════');
console.log('');
